
import java.awt.Container;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javafx.scene.paint.Color;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Aayush
 */
public class ADDMenu extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public ADDMenu() {
        initComponents();
        
           adl.show(false);
         upl.show(false);
         del.show(false);
         sel.show(false);
         lol.show(false);
        courseInput.setSelectedIndex(0);
                    theoryInput.setEnabled(false);

        PgMajor.setEnabled(false);
        LcodeInput.setEnabled(false);
        LabCredits.setEnabled(false);
        t6.setEnabled(false);
            t7.setEnabled(false);
            t8.setEnabled(false);
         t1.setEnabled(false);
            t2.setEnabled(false);
            t3.setEnabled(false);
            t4.setEnabled(false);
            t5.setEnabled(false);
           
              Credits.setEnabled(false);
               Addbutton.setToolTipText("ADD SYLLABUS");
         Updatebutton.setToolTipText("UPDATE SYLLABUS");
         Searchbutton.setToolTipText("SEARCH SYLLABUS");
          Deletebutton.setToolTipText("REMOVE/DELETE SYLLABUS");
          Logoutbutton.setToolTipText("LOGOUT");
           LnameInput.setEnabled(false);
            l1.setEnabled(false);
            l2.setEnabled(false);
            l3.setEnabled(false);
            l4.setEnabled(false);
            l5.setEnabled(false);
            
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Pack = new javax.swing.JPanel();
        ADD = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        Addbutton = new javax.swing.JButton();
        Updatebutton = new javax.swing.JButton();
        Searchbutton = new javax.swing.JButton();
        Deletebutton = new javax.swing.JButton();
        courseInput = new javax.swing.JComboBox<>();
        BranchInput = new javax.swing.JComboBox<>();
        schemeInput = new javax.swing.JComboBox<>();
        subLab = new javax.swing.JRadioButton();
        theoryInput = new javax.swing.JTabbedPane();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane9 = new javax.swing.JScrollPane();
        t1 = new javax.swing.JTextArea();
        jPanel10 = new javax.swing.JPanel();
        jScrollPane10 = new javax.swing.JScrollPane();
        t2 = new javax.swing.JTextArea();
        jPanel11 = new javax.swing.JPanel();
        jScrollPane11 = new javax.swing.JScrollPane();
        t3 = new javax.swing.JTextArea();
        jPanel12 = new javax.swing.JPanel();
        jScrollPane12 = new javax.swing.JScrollPane();
        t4 = new javax.swing.JTextArea();
        jPanel13 = new javax.swing.JPanel();
        jScrollPane13 = new javax.swing.JScrollPane();
        t5 = new javax.swing.JTextArea();
        p6 = new javax.swing.JPanel();
        tab6 = new javax.swing.JScrollPane();
        t6 = new javax.swing.JTextArea();
        tab7 = new javax.swing.JPanel();
        jScrollPane15 = new javax.swing.JScrollPane();
        t7 = new javax.swing.JTextArea();
        tab8 = new javax.swing.JPanel();
        jScrollPane16 = new javax.swing.JScrollPane();
        t8 = new javax.swing.JTextArea();
        LabContentInput = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        l1 = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        l2 = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        l3 = new javax.swing.JTextArea();
        jPanel4 = new javax.swing.JPanel();
        ip4 = new javax.swing.JScrollPane();
        l4 = new javax.swing.JTextArea();
        jPanel5 = new javax.swing.JPanel();
        ip5 = new javax.swing.JScrollPane();
        l5 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        subjectInput = new javax.swing.JTextField();
        hours = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        SemInput = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jButton10 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        LcodeInput = new javax.swing.JTextField();
        labCredits = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        LabCredits = new javax.swing.JTextField();
        subcodeInput = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        Credits = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Logoutbutton = new javax.swing.JButton();
        LnameInput = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        adl = new javax.swing.JLabel();
        upl = new javax.swing.JLabel();
        sel = new javax.swing.JLabel();
        del = new javax.swing.JLabel();
        lol = new javax.swing.JLabel();
        PgMajor = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("mainMenu"); // NOI18N

        Pack.setBackground(new java.awt.Color(0, 0, 51));
        Pack.setLayout(new java.awt.CardLayout());

        ADD.setLayout(null);

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 51));
        jLabel10.setText("Branch:");
        ADD.add(jLabel10);
        jLabel10.setBounds(80, 150, 90, 20);

        Addbutton.setForeground(new java.awt.Color(255, 255, 255));
        Addbutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/file.png"))); // NOI18N
        Addbutton.setContentAreaFilled(false);
        Addbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                AddbuttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                AddbuttonMouseExited(evt);
            }
        });
        Addbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddbuttonActionPerformed(evt);
            }
        });
        ADD.add(Addbutton);
        Addbutton.setBounds(280, 550, 120, 110);

        Updatebutton.setForeground(new java.awt.Color(255, 255, 255));
        Updatebutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/rotate.png"))); // NOI18N
        Updatebutton.setContentAreaFilled(false);
        Updatebutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                UpdatebuttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                UpdatebuttonMouseExited(evt);
            }
        });
        Updatebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdatebuttonActionPerformed(evt);
            }
        });
        ADD.add(Updatebutton);
        Updatebutton.setBounds(490, 550, 130, 110);

        Searchbutton.setForeground(new java.awt.Color(255, 255, 255));
        Searchbutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search (1).png"))); // NOI18N
        Searchbutton.setContentAreaFilled(false);
        Searchbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SearchbuttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SearchbuttonMouseExited(evt);
            }
        });
        Searchbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchbuttonActionPerformed(evt);
            }
        });
        ADD.add(Searchbutton);
        Searchbutton.setBounds(710, 560, 90, 90);

        Deletebutton.setForeground(new java.awt.Color(255, 255, 255));
        Deletebutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/shopping-basket.png"))); // NOI18N
        Deletebutton.setContentAreaFilled(false);
        Deletebutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                DeletebuttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                DeletebuttonMouseExited(evt);
            }
        });
        Deletebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeletebuttonActionPerformed(evt);
            }
        });
        ADD.add(Deletebutton);
        Deletebutton.setBounds(880, 560, 100, 90);

        courseInput.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "U.G", "P.G" }));
        courseInput.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                courseInputItemStateChanged(evt);
            }
        });
        courseInput.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                courseInputMouseClicked(evt);
            }
        });
        courseInput.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                courseInputInputMethodTextChanged(evt);
            }
        });
        courseInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                courseInputActionPerformed(evt);
            }
        });
        ADD.add(courseInput);
        courseInput.setBounds(170, 110, 80, 20);

        BranchInput.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CS", "EC", "EE", "Mech", "CV" }));
        ADD.add(BranchInput);
        BranchInput.setBounds(170, 150, 80, 20);

        schemeInput.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "select", "2010", "2015" }));
        schemeInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                schemeInputActionPerformed(evt);
            }
        });
        ADD.add(schemeInput);
        schemeInput.setBounds(170, 230, 80, 20);

        subLab.setBackground(new java.awt.Color(0, 0, 51));
        subLab.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        subLab.setForeground(new java.awt.Color(0, 0, 51));
        subLab.setText("Lab");
        subLab.setContentAreaFilled(false);
        subLab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subLabActionPerformed(evt);
            }
        });
        ADD.add(subLab);
        subLab.setBounds(170, 350, 51, 25);

        t1.setColumns(20);
        t1.setRows(5);
        jScrollPane9.setViewportView(t1);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane9, javax.swing.GroupLayout.DEFAULT_SIZE, 445, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane9, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE))
        );

        theoryInput.addTab("1", jPanel9);

        t2.setColumns(20);
        t2.setRows(5);
        jScrollPane10.setViewportView(t2);

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane10, javax.swing.GroupLayout.DEFAULT_SIZE, 445, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        theoryInput.addTab("2", jPanel10);

        t3.setColumns(20);
        t3.setRows(5);
        jScrollPane11.setViewportView(t3);

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane11, javax.swing.GroupLayout.DEFAULT_SIZE, 445, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        theoryInput.addTab("3", jPanel11);

        t4.setColumns(20);
        t4.setRows(5);
        jScrollPane12.setViewportView(t4);

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane12, javax.swing.GroupLayout.DEFAULT_SIZE, 445, Short.MAX_VALUE)
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        theoryInput.addTab("4", jPanel12);

        t5.setColumns(20);
        t5.setRows(5);
        jScrollPane13.setViewportView(t5);

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane13, javax.swing.GroupLayout.DEFAULT_SIZE, 445, Short.MAX_VALUE)
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane13, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        theoryInput.addTab("5", jPanel13);

        t6.setColumns(20);
        t6.setRows(5);
        tab6.setViewportView(t6);

        javax.swing.GroupLayout p6Layout = new javax.swing.GroupLayout(p6);
        p6.setLayout(p6Layout);
        p6Layout.setHorizontalGroup(
            p6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tab6, javax.swing.GroupLayout.DEFAULT_SIZE, 445, Short.MAX_VALUE)
        );
        p6Layout.setVerticalGroup(
            p6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p6Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(tab6, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        theoryInput.addTab("6", p6);

        t7.setColumns(20);
        t7.setRows(5);
        jScrollPane15.setViewportView(t7);

        javax.swing.GroupLayout tab7Layout = new javax.swing.GroupLayout(tab7);
        tab7.setLayout(tab7Layout);
        tab7Layout.setHorizontalGroup(
            tab7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane15, javax.swing.GroupLayout.DEFAULT_SIZE, 445, Short.MAX_VALUE)
        );
        tab7Layout.setVerticalGroup(
            tab7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tab7Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane15, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        theoryInput.addTab("7", tab7);

        t8.setColumns(20);
        t8.setRows(5);
        jScrollPane16.setViewportView(t8);

        javax.swing.GroupLayout tab8Layout = new javax.swing.GroupLayout(tab8);
        tab8.setLayout(tab8Layout);
        tab8Layout.setHorizontalGroup(
            tab8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane16, javax.swing.GroupLayout.DEFAULT_SIZE, 445, Short.MAX_VALUE)
        );
        tab8Layout.setVerticalGroup(
            tab8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tab8Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane16, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        theoryInput.addTab("8", tab8);

        ADD.add(theoryInput);
        theoryInput.setBounds(740, 120, 450, 100);

        l1.setColumns(20);
        l1.setRows(5);
        jScrollPane1.setViewportView(l1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 435, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        LabContentInput.addTab("1", jPanel1);

        l2.setColumns(20);
        l2.setRows(5);
        jScrollPane2.setViewportView(l2);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 435, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        LabContentInput.addTab("2", jPanel2);

        l3.setColumns(20);
        l3.setRows(5);
        jScrollPane3.setViewportView(l3);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 435, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        LabContentInput.addTab("3", jPanel3);

        l4.setColumns(20);
        l4.setRows(5);
        ip4.setViewportView(l4);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ip4, javax.swing.GroupLayout.DEFAULT_SIZE, 435, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(ip4, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        LabContentInput.addTab("4", jPanel4);

        l5.setColumns(20);
        l5.setRows(5);
        ip5.setViewportView(l5);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ip5, javax.swing.GroupLayout.DEFAULT_SIZE, 435, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(ip5, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        LabContentInput.addTab("5", jPanel5);

        ADD.add(LabContentInput);
        LabContentInput.setBounds(750, 360, 440, 100);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setForeground(new java.awt.Color(0, 0, 51));
        jLabel1.setText("Enter Programs content.");
        ADD.add(jLabel1);
        jLabel1.setBounds(750, 330, 150, 20);

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setForeground(new java.awt.Color(0, 0, 51));
        jLabel3.setText("Enter unit/module content.");
        ADD.add(jLabel3);
        jLabel3.setBounds(750, 80, 150, 14);

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 51));
        jLabel12.setText("Lab Name:");
        ADD.add(jLabel12);
        jLabel12.setBounds(60, 390, 110, 17);

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 51));
        jLabel13.setText("Add Syllabus :-");
        ADD.add(jLabel13);
        jLabel13.setBounds(10, 30, 130, 17);

        subjectInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subjectInputActionPerformed(evt);
            }
        });
        ADD.add(subjectInput);
        subjectInput.setBounds(170, 270, 140, 30);
        ADD.add(hours);
        hours.setBounds(450, 310, 60, 30);

        jLabel14.setBackground(new java.awt.Color(255, 255, 255));
        jLabel14.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 51));
        jLabel14.setText("Hours:");
        ADD.add(jLabel14);
        jLabel14.setBounds(370, 320, 80, 17);

        jLabel15.setBackground(new java.awt.Color(255, 255, 255));
        jLabel15.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 51));
        jLabel15.setText("Semester:");
        ADD.add(jLabel15);
        jLabel15.setBounds(60, 190, 110, 20);

        SemInput.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8" }));
        SemInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SemInputActionPerformed(evt);
            }
        });
        ADD.add(SemInput);
        SemInput.setBounds(170, 190, 50, 20);

        jLabel16.setBackground(new java.awt.Color(255, 255, 255));
        jLabel16.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 51));
        jLabel16.setText("Scheme:");
        ADD.add(jLabel16);
        jLabel16.setBounds(70, 230, 100, 20);

        jLabel17.setBackground(new java.awt.Color(255, 255, 255));
        jLabel17.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 51));
        jLabel17.setText("Course type:");
        ADD.add(jLabel17);
        jLabel17.setBounds(50, 110, 110, 17);

        jButton10.setText("Submit");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        ADD.add(jButton10);
        jButton10.setBounds(170, 480, 80, 23);

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setForeground(new java.awt.Color(0, 0, 51));
        jLabel4.setText("(specify PG Major)");
        ADD.add(jLabel4);
        jLabel4.setBounds(430, 110, 140, 14);

        LcodeInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LcodeInputActionPerformed(evt);
            }
        });
        ADD.add(LcodeInput);
        LcodeInput.setBounds(410, 380, 90, 30);

        labCredits.setBackground(new java.awt.Color(255, 255, 255));
        labCredits.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        labCredits.setForeground(new java.awt.Color(0, 0, 51));
        labCredits.setText("lab Credits:");
        ADD.add(labCredits);
        labCredits.setBounds(510, 390, 110, 20);

        jLabel19.setBackground(new java.awt.Color(255, 255, 255));
        jLabel19.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 0, 51));
        jLabel19.setText("Lab Code:");
        ADD.add(jLabel19);
        jLabel19.setBounds(320, 390, 90, 17);
        ADD.add(LabCredits);
        LabCredits.setBounds(630, 380, 60, 30);
        ADD.add(subcodeInput);
        subcodeInput.setBounds(450, 270, 90, 30);

        jLabel20.setBackground(new java.awt.Color(255, 255, 255));
        jLabel20.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 0, 51));
        jLabel20.setText(" Credits:");
        ADD.add(jLabel20);
        jLabel20.setBounds(70, 310, 90, 17);
        ADD.add(Credits);
        Credits.setBounds(170, 310, 60, 30);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Theory");
        ADD.add(jLabel2);
        jLabel2.setBounds(1130, 70, 60, 17);

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Lab");
        ADD.add(jLabel6);
        jLabel6.setBounds(1140, 300, 60, 17);

        Logoutbutton.setForeground(new java.awt.Color(255, 255, 255));
        Logoutbutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/door.png"))); // NOI18N
        Logoutbutton.setContentAreaFilled(false);
        Logoutbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LogoutbuttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LogoutbuttonMouseExited(evt);
            }
        });
        Logoutbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutbuttonActionPerformed(evt);
            }
        });
        ADD.add(Logoutbutton);
        Logoutbutton.setBounds(0, 570, 70, 70);

        LnameInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LnameInputActionPerformed(evt);
            }
        });
        ADD.add(LnameInput);
        LnameInput.setBounds(170, 380, 140, 30);

        jLabel21.setBackground(new java.awt.Color(255, 255, 255));
        jLabel21.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 0, 51));
        jLabel21.setText("Subject Code:");
        ADD.add(jLabel21);
        jLabel21.setBounds(320, 270, 110, 17);

        jLabel18.setBackground(new java.awt.Color(255, 255, 255));
        jLabel18.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 0, 51));
        jLabel18.setText("Subject Name:");
        ADD.add(jLabel18);
        jLabel18.setBounds(30, 270, 110, 17);

        jButton1.setText("Reset");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        ADD.add(jButton1);
        jButton1.setBounds(270, 480, 70, 23);

        adl.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        adl.setForeground(new java.awt.Color(0, 0, 51));
        adl.setText("ADD");
        ADD.add(adl);
        adl.setBounds(320, 530, 60, 17);

        upl.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        upl.setForeground(new java.awt.Color(0, 0, 51));
        upl.setText("Update");
        ADD.add(upl);
        upl.setBounds(540, 530, 100, 17);

        sel.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        sel.setForeground(new java.awt.Color(0, 0, 51));
        sel.setText("Search");
        ADD.add(sel);
        sel.setBounds(730, 530, 100, 17);

        del.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        del.setForeground(new java.awt.Color(0, 0, 51));
        del.setText("Delete");
        ADD.add(del);
        del.setBounds(910, 530, 90, 17);

        lol.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        lol.setForeground(new java.awt.Color(0, 0, 51));
        lol.setText("Logout");
        ADD.add(lol);
        lol.setBounds(20, 530, 120, 17);
        ADD.add(PgMajor);
        PgMajor.setBounds(310, 110, 90, 30);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add1.jpg"))); // NOI18N
        jLabel11.setText("jLabel11");
        ADD.add(jLabel11);
        jLabel11.setBounds(0, -10, 1220, 690);

        Pack.add(ADD, "card3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Pack, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1213, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Pack, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 675, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void subjectInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subjectInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_subjectInputActionPerformed

    private void LcodeInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LcodeInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LcodeInputActionPerformed

    private void schemeInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_schemeInputActionPerformed


        if(schemeInput.getSelectedItem().toString()=="2015")
        {
          theoryInput.setEnabled(true);
            
           
           Credits.setEnabled(true);
            t6.setEnabled(false);
            t7.setEnabled(false);
            t8.setEnabled(false);
             t1.setEnabled(true);
            t2.setEnabled(true);
            t3.setEnabled(true);
            t4.setEnabled(true);
            t5.setEnabled(true);
            if(subLab.isSelected())
            LabCredits.setEnabled(true);
        }
        else if(schemeInput.getSelectedItem().toString()=="2010")
        {
            theoryInput.setEnabled(true);
              Credits.setEnabled(false);
            t6.setEnabled(true);
            t7.setEnabled(true);
            t8.setEnabled(true);
             t1.setEnabled(true);
            t2.setEnabled(true);
            t3.setEnabled(true);
            t4.setEnabled(true);
            t5.setEnabled(true);
            LabCredits.setEnabled(false);

        }
        else if(schemeInput.getSelectedItem().toString()=="select")
        {
            theoryInput.setEnabled(false);
             Credits.setEnabled(false);
            t1.setEnabled(false);
            t2.setEnabled(false);
            t3.setEnabled(false);
            t4.setEnabled(false);
            t5.setEnabled(false);
            t6.setEnabled(false);
            t7.setEnabled(false);
            t8.setEnabled(false);
            
            
            LabCredits.setEnabled(false);
        }


        // TODO add your handling code here:
    }//GEN-LAST:event_schemeInputActionPerformed

    
    
    
    
   public boolean checkfullsyllabus()
   {
       boolean r=false;
       
       Container cn1[]=new Container[] {t1,t2,t3,t4,t5,t6,t7,t8};
       Container cn2[]=new Container[] {l1,l2,l3,l4,l5};
       
       if(!theoryInput.isEnabled())
       return false;
       
       for(int i=0;i<8;i++)
       {
           JTextArea ja=(JTextArea) cn1[i];
           if(ja.isEnabled() && (ja.getText().toString().length()<=0))
           
               return false;
           
               
           
           else
               r=true;
       }
       
       if(subLab.isSelected())
       {
        
           for(int i=0;i<5;i++)
       {
           JTextArea jb=(JTextArea) cn2[i];
           if(jb.isEnabled() && (jb.getText().toString().length()<=0))
               return false;
           else
               r=true;
       }
       }
       
       return r;

   }
    public boolean checkall()
            {
                boolean res=false;
                
                if(PgMajor.isEnabled() && (PgMajor.getText().toString().length()<=0))
                    return false;
                else 
                    res=true;
                
                if((subjectInput.getText().toString().length()<=0) || (subcodeInput.getText().toString().length()<=0) || (hours.getText().toString().length()<=0))
                    return false;
                else
                    res=true;
                    
                if(Credits.isEnabled() &&(Credits.getText().toString().length()<=0))
                    return false;
                else
                    res=true;
                if(subLab.isSelected())
                {
                    if((LnameInput.getText().toString().length()<=0) || (LcodeInput.getText().toString().length()<=0))
                        return false;
                    else
                        res=true;
                                
                    
                    if(LabCredits.isEnabled() && (LabCredits.getText().toString().length()<=0))
                        return false;
                    else
                        res=true;
                }
                
                res=checkfullsyllabus();
                
           return res;     
                
            }
    
    
    
    
    
    
    
    
    
    
    
    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed

      if(checkall()){  
        
        String course_type,postmajor="",stream,sem,year,sname,scode,hrs,cdts="",lcode="",lname="",lcdts="";
            String tmod[]=new String[10];
            String lmod[]=new String[10];
        Container tcont[]=new Container[] {t1,t2,t3,t4,t5,t6,t7,t8};
        Container lcont[]=new Container[] {l1,l2,l3,l4,l5};
        ResultSet rs;
        
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/syllabus?zeroDateTimeBehavior=convertToNull","root","");
            Statement stmt=con.createStatement();
            
             if(courseInput.getSelectedItem().toString()=="P.G")
             {
                 postmajor=PgMajor.getText();
                 course_type=courseInput.getSelectedItem().toString();
             }
             else
                 course_type=courseInput.getSelectedItem().toString();
            
             stream=BranchInput.getSelectedItem().toString();
             sem=SemInput.getSelectedItem().toString();
             
             if(schemeInput.getSelectedItem().toString()=="2015")
             {
                 year=schemeInput.getSelectedItem().toString();
                 cdts=Credits.getText();
                 
                 
                 for(int i=0;i<5;i++)
                 {
                     JTextArea j=(JTextArea) tcont[i];
                     tmod[i]=j.getText();
                     
                 }
                 
             }
             else
             {
                  year=schemeInput.getSelectedItem().toString();
                    for(int i=0;i<8;i++)
                 {
                     JTextArea j=(JTextArea) tcont[i];
                     tmod[i]=j.getText();
                     
                 }
             }
             
             
             
             
             
            sname=subjectInput.getText();
             scode=subcodeInput.getText();
             hrs=hours.getText();
             if(subLab.isSelected())
             {
                 lcode=LcodeInput.getText();
                 lname=LnameInput.getText();
                 lcdts=LabCredits.getText();
             }
             
             Boolean output=false;
           
              //adding subject
            stmt.executeUpdate("insert into `subject` (sname,scode,scheme,hours,ctype) values('"+sname+"','"+scode+"','"+year+"','"+hrs+"','"+course_type+"')");
            rs=stmt.executeQuery("select * from `subject` where scode='"+scode+"'");
            if(rs.next())
            {
                rs.close();
                    
       
                     //adding syllabus for theory
                   
                            int k=0;
                            while(tmod[k]!=null)
                            {
                                stmt.executeUpdate("insert into `subsyllabus` values('"+scode+"','"+(k+1)+"','"+tmod[k]+"')");
                                k+=1;
                            }
               
                            rs=stmt.executeQuery("select * from `subsyllabus` where scode='"+scode+"'");
                            if(rs.next())
                                {
                                  rs.close();
                                
                                     
                                      //adding syllabus for lab
                                            if(subLab.isSelected())
                                                {
                                                    for(int i=0;i<5;i++)
                                                        {
                                                            JTextArea m=(JTextArea) lcont[i];
                                                                lmod[i]=m.getText();
                                                        }
                  
                                                        int j=0;
                                                        while(lmod[j]!=null)
                                                        {
                                                        stmt.executeUpdate("insert into `labs` (scode,lcode,pno,content,lname,lcredits) values('"+scode+"','"+lcode+"','"+(j+1)+"','"+lmod[j]+"','"+lname+"','"+lcdts+"')");
                                                        j++;
                                                        }
                  
                                                        rs=stmt.executeQuery("select * from `labs` where lcode='"+lcode+"'");
                  
                                                        if(!rs.next())
                                                        {
                                                
                                                        JOptionPane.showMessageDialog(rootPane,"error while adding lab");
                                                        }
                                                        rs.close();
                                                }
                                    
                                       //adding in course
                                       if(courseInput.getSelectedItem().toString()=="P.G"){
                                      stmt.executeUpdate("insert into `course` values('"+postmajor+"','"+scode+"')");
                                      rs=stmt.executeQuery("select * from `course` where scode='"+scode+"'");
                                      if(rs.next())
                                      {
                                         rs.close();
                                            //adding department
                                                /*stmt.executeUpdate("insert into `department` values('"+stream+"','"+sem+"','"+scode+"')");
                                                rs=stmt.executeQuery("select * from `department`");
                                                if(rs.next())
                                                {
                                                    rs.close();
                                                    JOptionPane.showMessageDialog(rootPane,"Successful");
                                          
                                                }
                                                else
                                                {
                                                    JOptionPane.showMessageDialog(rootPane,"error while adding department");
                                                }*/
                                    
                                      }
                                      else
                                        {
                                         JOptionPane.showMessageDialog(rootPane,"error while adding course");
                                        }
                                       }
                                       //adding credits
                                       if(schemeInput.getSelectedItem().toString()=="2015")
                                       {
                                           int xyz=stmt.executeUpdate("insert into credits values('"+scode+"','"+cdts+"')");
                                           rs=stmt.executeQuery("select * from credits where scode='"+scode+"'");
                                           if(!rs.next())
                                           {
                                               JOptionPane.showMessageDialog(null,"error in credits");
                                               
                                           }
                                           rs.close();
                                           
                                       }
                                       
                                       //adding department
                                                stmt.executeUpdate("insert into `department` values('"+stream+"','"+sem+"','"+scode+"')");
                                                rs=stmt.executeQuery("select * from `department` where scode='"+scode+"'");
                                                if(rs.next())
                                                {
                                                    rs.close();
                                                    JOptionPane.showMessageDialog(rootPane,"Successful");
                                          
                                                }
                                                else
                                                {
                                                    JOptionPane.showMessageDialog(rootPane,"error while adding department");
                                                }
                                                
                                                
                                }
                                  else
                                    {
                                        JOptionPane.showMessageDialog(rootPane,"error while adding Syllabus");
                                    }
                                            
                                            
            }
            else
                {
                    JOptionPane.showMessageDialog(rootPane,"error in adding subject");
                }
          
                                                   
            // TODO add your handling code here:
        } catch (ClassNotFoundException ex) {
           // Logger.getLogger(ADDMenu.class.getName()).log(Level.SEVERE, null, ex);
      
        } catch (SQLException ex) {
           // Logger.getLogger(ADDMenu.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(rootPane,ex,"Error",JOptionPane.ERROR_MESSAGE);
        }
        
        
        
      }//end checkall
      else
      {
          JOptionPane.showMessageDialog(null,"fields left blank","error",JOptionPane.ERROR_MESSAGE);
      }
    }//GEN-LAST:event_jButton10ActionPerformed

    
    
    
    
    private void courseInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_courseInputActionPerformed


          if(courseInput.getSelectedItem().toString()=="P.G")
          {
          
                PgMajor.setEnabled(true);
                if(Integer.parseInt(SemInput.getSelectedItem().toString())>4)
            {
                JOptionPane.showMessageDialog(null,"Selection of semester above 4th is not allowed in P.G","error", JOptionPane.ERROR_MESSAGE);
                SemInput.setSelectedIndex(0);
            }
          }
            else
                PgMajor.setEnabled(false);
                

 


        // TODO add your handling code here:
    }//GEN-LAST:event_courseInputActionPerformed

    private void courseInputItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_courseInputItemStateChanged
     
 // TODO add your handling code here:
    }//GEN-LAST:event_courseInputItemStateChanged

    private void courseInputMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_courseInputMouseClicked
          
 // TODO add your handling code here:
    }//GEN-LAST:event_courseInputMouseClicked

    private void courseInputInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_courseInputInputMethodTextChanged

 

        // TODO add your handling code here:
    }//GEN-LAST:event_courseInputInputMethodTextChanged

    private void subLabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subLabActionPerformed

        // TODO add your handling code here:
    
        if(subLab.isSelected())
        {
            
            if(schemeInput.getSelectedItem().toString()=="2015")
                LabCredits.setEnabled(true);
            else
                LabCredits.setEnabled(false);
            
            LcodeInput.setEnabled(true);
            LnameInput.setEnabled(true);
                  l1.setEnabled(true);
            l2.setEnabled(true);
            l3.setEnabled(true);
            l4.setEnabled(true);
            l5.setEnabled(true);
            
          
        }
        else{
            LcodeInput.setEnabled(false);
            LnameInput.setEnabled(false);
            LabCredits.setEnabled(false);
           
             l1.setEnabled(false);
            l2.setEnabled(false);
            l3.setEnabled(false);
            l4.setEnabled(false);
            l5.setEnabled(false);
            
        }
          
       
        
    }//GEN-LAST:event_subLabActionPerformed

    private void LnameInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LnameInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LnameInputActionPerformed

    private void AddbuttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddbuttonMouseEntered
adl.show(true);        // TODO add your handling code here:
    }//GEN-LAST:event_AddbuttonMouseEntered

    private void UpdatebuttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UpdatebuttonMouseEntered
upl.show(true);        // TODO add your handling code here:
    }//GEN-LAST:event_UpdatebuttonMouseEntered

    private void AddbuttonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddbuttonMouseExited
adl.show(false);        // TODO add your handling code here:
    }//GEN-LAST:event_AddbuttonMouseExited

    private void UpdatebuttonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UpdatebuttonMouseExited
upl.show(false);        // TODO add your handling code here:
    }//GEN-LAST:event_UpdatebuttonMouseExited

    private void SearchbuttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SearchbuttonMouseEntered
sel.show(true);        // TODO add your handling code here:
    }//GEN-LAST:event_SearchbuttonMouseEntered

    private void SearchbuttonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SearchbuttonMouseExited
sel.show(false);        // TODO add your handling code here:
    }//GEN-LAST:event_SearchbuttonMouseExited

    private void DeletebuttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DeletebuttonMouseEntered
del.show(true);
del.setBackground(java.awt.Color.LIGHT_GRAY);// TODO add your handling code here:
    }//GEN-LAST:event_DeletebuttonMouseEntered

    private void DeletebuttonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DeletebuttonMouseExited
del.show(false);        // TODO add your handling code here:
    }//GEN-LAST:event_DeletebuttonMouseExited

    private void AddbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddbuttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddbuttonActionPerformed

    private void UpdatebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdatebuttonActionPerformed
                UpdateMenu up=new UpdateMenu();
                up.setVisible(true);
                this.dispose();
// TODO add your handling code here:
    }//GEN-LAST:event_UpdatebuttonActionPerformed

    private void SearchbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchbuttonActionPerformed
      new Search(false).setVisible(true);
      this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_SearchbuttonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        courseInput.setSelectedIndex(0);
         BranchInput.setSelectedIndex(0);
        SemInput.setSelectedIndex(0);
        schemeInput.setSelectedIndex(0);
        PgMajor.setText("");
         subjectInput.setText("");
          subcodeInput.setText("");
          Credits.setText("");
          hours.setText("");
          subLab.setSelected(false);
           LnameInput.setText("");
            LcodeInput.setText("");
            LabCredits.setText("");
        t1.setText("");
        t2.setText("");
        t3.setText("");
        t4.setText("");
        t5.setText("");
        t6.setText("");
        t7.setText("");
        t8.setText("");
        l1.setText("");
        l2.setText("");
        l3.setText("");
        l4.setText("");
        l5.setText("");
 LnameInput.setEnabled(false);
        courseInput.setSelectedIndex(0);
        PgMajor.setEnabled(false);
        LcodeInput.setEnabled(false);
        LabCredits.setEnabled(false);
        t6.setEnabled(false);
            t7.setEnabled(false);
            t8.setEnabled(false);
         
           LabContentInput.setEnabled(false);
              Credits.setEnabled(false);



        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void SemInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SemInputActionPerformed
        if(courseInput.getSelectedItem().toString()=="P.G")
        {
            if(Integer.parseInt(SemInput.getSelectedItem().toString())>4)
            {
                JOptionPane.showMessageDialog(null,"Selection of semester above 4th is not allowed in P.G","error", JOptionPane.ERROR_MESSAGE);
                SemInput.setSelectedIndex(0);
            }
        }


        // TODO add your handling code here:
    }//GEN-LAST:event_SemInputActionPerformed

    private void LogoutbuttonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutbuttonMouseExited
        lol.show(false);        // TODO add your handling code here:
    }//GEN-LAST:event_LogoutbuttonMouseExited

    private void LogoutbuttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutbuttonMouseEntered
        lol.show(true);        // TODO add your handling code here:
    }//GEN-LAST:event_LogoutbuttonMouseEntered

    private void LogoutbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutbuttonActionPerformed
new Start(true).setVisible(true);
this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_LogoutbuttonActionPerformed

    private void DeletebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeletebuttonActionPerformed
Search sc=new Search(false);
sc.setButton();
sc.setVisible(true);
this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_DeletebuttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ADDMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ADDMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ADDMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ADDMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ADDMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ADD;
    private javax.swing.JButton Addbutton;
    private javax.swing.JComboBox<String> BranchInput;
    private javax.swing.JTextField Credits;
    private javax.swing.JButton Deletebutton;
    private javax.swing.JTabbedPane LabContentInput;
    private javax.swing.JTextField LabCredits;
    private javax.swing.JTextField LcodeInput;
    private javax.swing.JTextField LnameInput;
    private javax.swing.JButton Logoutbutton;
    private javax.swing.JPanel Pack;
    private javax.swing.JTextField PgMajor;
    private javax.swing.JButton Searchbutton;
    private javax.swing.JComboBox<String> SemInput;
    private javax.swing.JButton Updatebutton;
    private javax.swing.JLabel adl;
    private javax.swing.JComboBox<String> courseInput;
    private javax.swing.JLabel del;
    private javax.swing.JTextField hours;
    private javax.swing.JScrollPane ip4;
    private javax.swing.JScrollPane ip5;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JScrollPane jScrollPane15;
    private javax.swing.JScrollPane jScrollPane16;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTextArea l1;
    private javax.swing.JTextArea l2;
    private javax.swing.JTextArea l3;
    private javax.swing.JTextArea l4;
    private javax.swing.JTextArea l5;
    private javax.swing.JLabel labCredits;
    private javax.swing.JLabel lol;
    private javax.swing.JPanel p6;
    private javax.swing.JComboBox<String> schemeInput;
    private javax.swing.JLabel sel;
    private javax.swing.JRadioButton subLab;
    private javax.swing.JTextField subcodeInput;
    private javax.swing.JTextField subjectInput;
    private javax.swing.JTextArea t1;
    private javax.swing.JTextArea t2;
    private javax.swing.JTextArea t3;
    private javax.swing.JTextArea t4;
    private javax.swing.JTextArea t5;
    private javax.swing.JTextArea t6;
    private javax.swing.JTextArea t7;
    private javax.swing.JTextArea t8;
    private javax.swing.JScrollPane tab6;
    private javax.swing.JPanel tab7;
    private javax.swing.JPanel tab8;
    private javax.swing.JTabbedPane theoryInput;
    private javax.swing.JLabel upl;
    // End of variables declaration//GEN-END:variables
}
