
import java.awt.Container;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Aayush
 */
public class Delete extends javax.swing.JFrame {

    /**
     * Creates new form Delete
     */
      String branch;
     Connection con;
    Statement stmt;
    ResultSet rs;
    public Delete() {
        initComponents();
         ldeptip.setEnabled(false);
            lsembt.setEnabled(false);
            lsemip.setEnabled(false);
            lsubip.setEnabled(false);
            
        
        lscodeip.setEnabled(false);
        labcodeip.setEnabled(false);
        
         adl2.show(false);
        upl2.show(false);
        sel2.show(false);
        del2.show(false);
        lol2.show(false);
        majorbt.setEnabled(false);
        majorip.setEnabled(false);
        
        adl.show(false);
        upl.show(false);
        sel.show(false);
        del.show(false);
        lol.show(false);
       
       
       
        scodeip.setEnabled(false);
        deptip.setEnabled(false);
        sembt.setEnabled(false);
        semip.setEnabled(false);
        subip1.setEnabled(false);
        courseip.setEnabled(false);
        subip2.setEnabled(false);
        schemeip.setEnabled(false);
        subip3.setEnabled(false);
         try{
         Class.forName("com.mysql.jdbc.Driver");
            con=DriverManager.getConnection("jdbc:mysql://localhost:3306/syllabus?zeroDateTimeBehavior=convertToNull","root","");
            stmt=con.createStatement();
    }        catch (ClassNotFoundException ex) {
                 Logger.getLogger(Search.class.getName()).log(Level.SEVERE, null, ex);
             } catch (SQLException ex) {
                 Logger.getLogger(Search.class.getName()).log(Level.SEVERE, null, ex);
             }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Pack = new javax.swing.JPanel();
        Theory = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        scodebt = new javax.swing.JRadioButton();
        sembt = new javax.swing.JRadioButton();
        coursebt = new javax.swing.JRadioButton();
        schemebt = new javax.swing.JRadioButton();
        Logoutbutton = new javax.swing.JButton();
        lol = new javax.swing.JLabel();
        Addbutton = new javax.swing.JButton();
        adl = new javax.swing.JLabel();
        upl = new javax.swing.JLabel();
        Updatebutton = new javax.swing.JButton();
        sel = new javax.swing.JLabel();
        Searchbutton = new javax.swing.JButton();
        del = new javax.swing.JLabel();
        Deletebutton = new javax.swing.JButton();
        deptbt = new javax.swing.JRadioButton();
        subip2 = new javax.swing.JComboBox<>();
        subip3 = new javax.swing.JComboBox<>();
        subip1 = new javax.swing.JComboBox<>();
        scodeip = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        deptip = new javax.swing.JComboBox<>();
        semip = new javax.swing.JComboBox<>();
        courseip = new javax.swing.JComboBox<>();
        schemeip = new javax.swing.JComboBox<>();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        gotolab = new javax.swing.JButton();
        jSeparator11 = new javax.swing.JSeparator();
        majorip = new javax.swing.JComboBox<>();
        majorbt = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        Lab = new javax.swing.JPanel();
        lscodebt = new javax.swing.JRadioButton();
        jLabel21 = new javax.swing.JLabel();
        jSeparator9 = new javax.swing.JSeparator();
        lscodeip = new javax.swing.JTextField();
        labcodebt = new javax.swing.JRadioButton();
        jLabel22 = new javax.swing.JLabel();
        jSeparator10 = new javax.swing.JSeparator();
        labcodeip = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        Logoutbutton2 = new javax.swing.JButton();
        lol2 = new javax.swing.JLabel();
        adl2 = new javax.swing.JLabel();
        Addbutton2 = new javax.swing.JButton();
        upl2 = new javax.swing.JLabel();
        Updatebutton2 = new javax.swing.JButton();
        sel2 = new javax.swing.JLabel();
        Searchbutton2 = new javax.swing.JButton();
        del2 = new javax.swing.JLabel();
        Deletebutton2 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        ldeptbt = new javax.swing.JRadioButton();
        jSeparator12 = new javax.swing.JSeparator();
        jLabel24 = new javax.swing.JLabel();
        ldeptip = new javax.swing.JComboBox<>();
        lsembt = new javax.swing.JRadioButton();
        jSeparator13 = new javax.swing.JSeparator();
        lsemip = new javax.swing.JComboBox<>();
        jLabel25 = new javax.swing.JLabel();
        jSeparator14 = new javax.swing.JSeparator();
        lsubip = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Pack.setLayout(new java.awt.CardLayout());

        Theory.setLayout(null);

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 51));
        jLabel13.setText("Subject Code:");
        Theory.add(jLabel13);
        jLabel13.setBounds(10, 220, 130, 17);

        scodebt.setBackground(new java.awt.Color(0, 0, 51));
        scodebt.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        scodebt.setForeground(new java.awt.Color(0, 0, 51));
        scodebt.setText("By Subject Code-");
        scodebt.setContentAreaFilled(false);
        scodebt.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                scodebtItemStateChanged(evt);
            }
        });
        scodebt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scodebtActionPerformed(evt);
            }
        });
        Theory.add(scodebt);
        scodebt.setBounds(10, 140, 210, 25);

        sembt.setBackground(new java.awt.Color(0, 0, 51));
        sembt.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        sembt.setForeground(new java.awt.Color(0, 0, 51));
        sembt.setText("Sem:");
        sembt.setContentAreaFilled(false);
        sembt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sembtActionPerformed(evt);
            }
        });
        Theory.add(sembt);
        sembt.setBounds(360, 320, 90, 20);

        coursebt.setBackground(new java.awt.Color(0, 0, 51));
        coursebt.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        coursebt.setForeground(new java.awt.Color(0, 0, 51));
        coursebt.setText("By Course-");
        coursebt.setContentAreaFilled(false);
        coursebt.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                coursebtItemStateChanged(evt);
            }
        });
        coursebt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                coursebtActionPerformed(evt);
            }
        });
        Theory.add(coursebt);
        coursebt.setBounds(670, 140, 220, 25);

        schemebt.setBackground(new java.awt.Color(0, 0, 51));
        schemebt.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        schemebt.setForeground(new java.awt.Color(0, 0, 51));
        schemebt.setText("By Scheme-");
        schemebt.setContentAreaFilled(false);
        schemebt.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                schemebtItemStateChanged(evt);
            }
        });
        schemebt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                schemebtActionPerformed(evt);
            }
        });
        Theory.add(schemebt);
        schemebt.setBounds(970, 140, 210, 25);

        Logoutbutton.setBackground(new java.awt.Color(255, 255, 255));
        Logoutbutton.setFont(new java.awt.Font("Tahoma", 0, 3)); // NOI18N
        Logoutbutton.setForeground(new java.awt.Color(255, 255, 255));
        Logoutbutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/door.png"))); // NOI18N
        Logoutbutton.setText("v");
        Logoutbutton.setContentAreaFilled(false);
        Logoutbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LogoutbuttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LogoutbuttonMouseExited(evt);
            }
        });
        Logoutbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutbuttonActionPerformed(evt);
            }
        });
        Theory.add(Logoutbutton);
        Logoutbutton.setBounds(10, 577, 50, 73);

        lol.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        lol.setForeground(new java.awt.Color(0, 0, 51));
        lol.setText("Logout");
        Theory.add(lol);
        lol.setBounds(10, 530, 120, 17);

        Addbutton.setForeground(new java.awt.Color(255, 255, 255));
        Addbutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/file.png"))); // NOI18N
        Addbutton.setContentAreaFilled(false);
        Addbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                AddbuttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                AddbuttonMouseExited(evt);
            }
        });
        Addbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddbuttonActionPerformed(evt);
            }
        });
        Theory.add(Addbutton);
        Addbutton.setBounds(290, 560, 100, 100);

        adl.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        adl.setForeground(new java.awt.Color(0, 0, 51));
        adl.setText("ADD");
        Theory.add(adl);
        adl.setBounds(330, 530, 60, 17);

        upl.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        upl.setForeground(new java.awt.Color(0, 0, 51));
        upl.setText("Update");
        Theory.add(upl);
        upl.setBounds(530, 530, 100, 17);

        Updatebutton.setBackground(new java.awt.Color(255, 255, 255));
        Updatebutton.setFont(new java.awt.Font("Tahoma", 0, 3)); // NOI18N
        Updatebutton.setForeground(new java.awt.Color(255, 255, 255));
        Updatebutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/rotate.png"))); // NOI18N
        Updatebutton.setText("m");
        Updatebutton.setContentAreaFilled(false);
        Updatebutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                UpdatebuttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                UpdatebuttonMouseExited(evt);
            }
        });
        Updatebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdatebuttonActionPerformed(evt);
            }
        });
        Theory.add(Updatebutton);
        Updatebutton.setBounds(510, 577, 90, 73);

        sel.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        sel.setForeground(new java.awt.Color(0, 0, 51));
        sel.setText("Search");
        Theory.add(sel);
        sel.setBounds(730, 530, 100, 17);

        Searchbutton.setForeground(new java.awt.Color(255, 255, 255));
        Searchbutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search (1).png"))); // NOI18N
        Searchbutton.setContentAreaFilled(false);
        Searchbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SearchbuttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SearchbuttonMouseExited(evt);
            }
        });
        Searchbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchbuttonActionPerformed(evt);
            }
        });
        Theory.add(Searchbutton);
        Searchbutton.setBounds(700, 570, 110, 90);

        del.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        del.setForeground(new java.awt.Color(0, 0, 51));
        del.setText("Delete");
        Theory.add(del);
        del.setBounds(910, 530, 90, 17);

        Deletebutton.setForeground(new java.awt.Color(255, 255, 255));
        Deletebutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/shopping-basket.png"))); // NOI18N
        Deletebutton.setContentAreaFilled(false);
        Deletebutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                DeletebuttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                DeletebuttonMouseExited(evt);
            }
        });
        Deletebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeletebuttonActionPerformed(evt);
            }
        });
        Theory.add(Deletebutton);
        Deletebutton.setBounds(880, 560, 100, 100);

        deptbt.setBackground(new java.awt.Color(0, 0, 51));
        deptbt.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        deptbt.setForeground(new java.awt.Color(0, 0, 51));
        deptbt.setText("By Department- ");
        deptbt.setContentAreaFilled(false);
        deptbt.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                deptbtItemStateChanged(evt);
            }
        });
        deptbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deptbtActionPerformed(evt);
            }
        });
        Theory.add(deptbt);
        deptbt.setBounds(360, 140, 220, 25);

        subip2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subip2ActionPerformed(evt);
            }
        });
        Theory.add(subip2);
        subip2.setBounds(700, 430, 160, 30);

        subip3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subip3ActionPerformed(evt);
            }
        });
        Theory.add(subip3);
        subip3.setBounds(980, 350, 160, 30);

        subip1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subip1ActionPerformed(evt);
            }
        });
        Theory.add(subip1);
        subip1.setBounds(360, 430, 160, 30);

        scodeip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scodeipActionPerformed(evt);
            }
        });
        Theory.add(scodeip);
        scodeip.setBounds(10, 260, 140, 30);

        jLabel14.setBackground(new java.awt.Color(255, 255, 255));
        jLabel14.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 51));
        jLabel14.setText("Department:");
        Theory.add(jLabel14);
        jLabel14.setBounds(360, 220, 130, 17);

        jLabel15.setBackground(new java.awt.Color(255, 255, 255));
        jLabel15.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 51));
        jLabel15.setText("Select subject:");
        Theory.add(jLabel15);
        jLabel15.setBounds(360, 400, 110, 17);

        jLabel16.setBackground(new java.awt.Color(255, 255, 255));
        jLabel16.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 51));
        jLabel16.setText("Course:");
        Theory.add(jLabel16);
        jLabel16.setBounds(700, 220, 130, 17);

        jLabel17.setBackground(new java.awt.Color(255, 255, 255));
        jLabel17.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 51));
        jLabel17.setText("Select subject:");
        Theory.add(jLabel17);
        jLabel17.setBounds(700, 400, 120, 17);

        jLabel18.setBackground(new java.awt.Color(255, 255, 255));
        jLabel18.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 0, 51));
        jLabel18.setText("Scheme:");
        Theory.add(jLabel18);
        jLabel18.setBounds(980, 220, 130, 17);

        jLabel19.setBackground(new java.awt.Color(255, 255, 255));
        jLabel19.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 0, 51));
        jLabel19.setText("Select subject:");
        Theory.add(jLabel19);
        jLabel19.setBounds(980, 320, 130, 17);

        jLabel20.setBackground(new java.awt.Color(255, 255, 255));
        jLabel20.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 0, 51));
        jLabel20.setText("Delete subject");
        Theory.add(jLabel20);
        jLabel20.setBounds(10, 40, 130, 17);

        deptip.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "CS", "EC", "EE", "Mech", "CV" }));
        deptip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deptipActionPerformed(evt);
            }
        });
        Theory.add(deptip);
        deptip.setBounds(360, 250, 90, 20);

        semip.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "1", "2", "3", "4", "5", "6", "7", "8" }));
        semip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                semipActionPerformed(evt);
            }
        });
        Theory.add(semip);
        semip.setBounds(360, 350, 90, 20);

        courseip.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "select", "U.G", "P.G" }));
        courseip.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                courseipItemStateChanged(evt);
            }
        });
        courseip.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                courseipMouseClicked(evt);
            }
        });
        courseip.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                courseipInputMethodTextChanged(evt);
            }
        });
        courseip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                courseipActionPerformed(evt);
            }
        });
        Theory.add(courseip);
        courseip.setBounds(700, 250, 80, 20);

        schemeip.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "2010", "2015" }));
        schemeip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                schemeipActionPerformed(evt);
            }
        });
        Theory.add(schemeip);
        schemeip.setBounds(980, 250, 80, 20);
        Theory.add(jSeparator1);
        jSeparator1.setBounds(360, 240, 160, 10);
        Theory.add(jSeparator2);
        jSeparator2.setBounds(360, 340, 110, 10);
        Theory.add(jSeparator3);
        jSeparator3.setBounds(360, 420, 160, 10);
        Theory.add(jSeparator4);
        jSeparator4.setBounds(700, 340, 160, 10);
        Theory.add(jSeparator5);
        jSeparator5.setBounds(700, 420, 160, 10);
        Theory.add(jSeparator6);
        jSeparator6.setBounds(980, 240, 160, 10);
        Theory.add(jSeparator7);
        jSeparator7.setBounds(980, 340, 160, 10);
        Theory.add(jSeparator8);
        jSeparator8.setBounds(10, 242, 160, 10);

        jButton1.setText("Delete");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        Theory.add(jButton1);
        jButton1.setBounds(1045, 440, 90, 23);

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Theory");
        Theory.add(jLabel7);
        jLabel7.setBounds(910, 20, 100, 22);

        jLabel8.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Lab");
        Theory.add(jLabel8);
        jLabel8.setBounds(1050, 0, 70, 22);

        gotolab.setBorderPainted(false);
        gotolab.setContentAreaFilled(false);
        gotolab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gotolabActionPerformed(evt);
            }
        });
        Theory.add(gotolab);
        gotolab.setBounds(1020, 0, 110, 30);
        Theory.add(jSeparator11);
        jSeparator11.setBounds(700, 240, 160, 10);

        majorip.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                majoripItemStateChanged(evt);
            }
        });
        majorip.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                majoripMouseClicked(evt);
            }
        });
        majorip.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                majoripInputMethodTextChanged(evt);
            }
        });
        majorip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                majoripActionPerformed(evt);
            }
        });
        Theory.add(majorip);
        majorip.setBounds(700, 350, 80, 20);

        majorbt.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        majorbt.setForeground(new java.awt.Color(0, 0, 51));
        majorbt.setText("Major:");
        majorbt.setContentAreaFilled(false);
        majorbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                majorbtActionPerformed(evt);
            }
        });
        Theory.add(majorbt);
        majorbt.setBounds(700, 320, 93, 23);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search1.jpg"))); // NOI18N
        Theory.add(jLabel1);
        jLabel1.setBounds(0, 0, 1590, 680);

        Pack.add(Theory, "card2");

        Lab.setLayout(null);

        lscodebt.setBackground(new java.awt.Color(0, 0, 51));
        lscodebt.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        lscodebt.setForeground(new java.awt.Color(0, 0, 51));
        lscodebt.setText("By Subject Code-");
        lscodebt.setContentAreaFilled(false);
        lscodebt.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                lscodebtItemStateChanged(evt);
            }
        });
        lscodebt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lscodebtActionPerformed(evt);
            }
        });
        Lab.add(lscodebt);
        lscodebt.setBounds(30, 140, 210, 25);

        jLabel21.setBackground(new java.awt.Color(255, 255, 255));
        jLabel21.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 0, 51));
        jLabel21.setText("Subject Code:");
        Lab.add(jLabel21);
        jLabel21.setBounds(40, 200, 130, 17);
        Lab.add(jSeparator9);
        jSeparator9.setBounds(40, 220, 170, 10);

        lscodeip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lscodeipActionPerformed(evt);
            }
        });
        Lab.add(lscodeip);
        lscodeip.setBounds(40, 240, 140, 30);

        labcodebt.setBackground(new java.awt.Color(0, 0, 51));
        labcodebt.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        labcodebt.setForeground(new java.awt.Color(0, 0, 51));
        labcodebt.setText("By Lab Code-");
        labcodebt.setContentAreaFilled(false);
        labcodebt.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                labcodebtItemStateChanged(evt);
            }
        });
        labcodebt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                labcodebtActionPerformed(evt);
            }
        });
        Lab.add(labcodebt);
        labcodebt.setBounds(460, 140, 210, 25);

        jLabel22.setBackground(new java.awt.Color(255, 255, 255));
        jLabel22.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(0, 0, 51));
        jLabel22.setText("Department:");
        Lab.add(jLabel22);
        jLabel22.setBounds(900, 200, 120, 20);
        Lab.add(jSeparator10);
        jSeparator10.setBounds(900, 220, 160, 10);

        labcodeip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                labcodeipActionPerformed(evt);
            }
        });
        Lab.add(labcodeip);
        labcodeip.setBounds(460, 240, 140, 30);

        jLabel23.setBackground(new java.awt.Color(255, 255, 255));
        jLabel23.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(0, 0, 51));
        jLabel23.setText("Delete lab:-");
        Lab.add(jLabel23);
        jLabel23.setBounds(10, 40, 130, 17);

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Theory");
        Lab.add(jLabel9);
        jLabel9.setBounds(910, 0, 100, 22);

        jLabel10.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Lab");
        Lab.add(jLabel10);
        jLabel10.setBounds(1050, 20, 70, 22);

        Logoutbutton2.setBackground(new java.awt.Color(255, 255, 255));
        Logoutbutton2.setFont(new java.awt.Font("Tahoma", 0, 3)); // NOI18N
        Logoutbutton2.setForeground(new java.awt.Color(255, 255, 255));
        Logoutbutton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/door.png"))); // NOI18N
        Logoutbutton2.setText("v");
        Logoutbutton2.setContentAreaFilled(false);
        Logoutbutton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Logoutbutton2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Logoutbutton2MouseExited(evt);
            }
        });
        Logoutbutton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Logoutbutton2ActionPerformed(evt);
            }
        });
        Lab.add(Logoutbutton2);
        Logoutbutton2.setBounds(0, 570, 70, 90);

        lol2.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        lol2.setForeground(new java.awt.Color(0, 0, 51));
        lol2.setText("Logout");
        Lab.add(lol2);
        lol2.setBounds(20, 530, 120, 17);

        adl2.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        adl2.setForeground(new java.awt.Color(0, 0, 51));
        adl2.setText("ADD");
        Lab.add(adl2);
        adl2.setBounds(330, 540, 60, 17);

        Addbutton2.setForeground(new java.awt.Color(255, 255, 255));
        Addbutton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/file.png"))); // NOI18N
        Addbutton2.setContentAreaFilled(false);
        Addbutton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Addbutton2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Addbutton2MouseExited(evt);
            }
        });
        Addbutton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Addbutton2ActionPerformed(evt);
            }
        });
        Lab.add(Addbutton2);
        Addbutton2.setBounds(290, 560, 100, 110);

        upl2.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        upl2.setForeground(new java.awt.Color(0, 0, 51));
        upl2.setText("Update");
        Lab.add(upl2);
        upl2.setBounds(540, 540, 100, 17);

        Updatebutton2.setBackground(new java.awt.Color(255, 255, 255));
        Updatebutton2.setFont(new java.awt.Font("Tahoma", 0, 3)); // NOI18N
        Updatebutton2.setForeground(new java.awt.Color(255, 255, 255));
        Updatebutton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/rotate.png"))); // NOI18N
        Updatebutton2.setText("v");
        Updatebutton2.setContentAreaFilled(false);
        Updatebutton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Updatebutton2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Updatebutton2MouseExited(evt);
            }
        });
        Updatebutton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Updatebutton2ActionPerformed(evt);
            }
        });
        Lab.add(Updatebutton2);
        Updatebutton2.setBounds(510, 570, 90, 90);

        sel2.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        sel2.setForeground(new java.awt.Color(0, 0, 51));
        sel2.setText("Search");
        Lab.add(sel2);
        sel2.setBounds(740, 540, 100, 17);

        Searchbutton2.setForeground(new java.awt.Color(255, 255, 255));
        Searchbutton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search (1).png"))); // NOI18N
        Searchbutton2.setContentAreaFilled(false);
        Searchbutton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Searchbutton2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Searchbutton2MouseExited(evt);
            }
        });
        Lab.add(Searchbutton2);
        Searchbutton2.setBounds(700, 570, 110, 90);

        del2.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        del2.setForeground(new java.awt.Color(0, 0, 51));
        del2.setText("Delete");
        Lab.add(del2);
        del2.setBounds(910, 540, 90, 17);

        Deletebutton2.setForeground(new java.awt.Color(255, 255, 255));
        Deletebutton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/shopping-basket.png"))); // NOI18N
        Deletebutton2.setContentAreaFilled(false);
        Deletebutton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Deletebutton2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Deletebutton2MouseExited(evt);
            }
        });
        Deletebutton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Deletebutton2ActionPerformed(evt);
            }
        });
        Lab.add(Deletebutton2);
        Deletebutton2.setBounds(870, 560, 120, 110);

        jButton2.setText("Submit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        Lab.add(jButton2);
        jButton2.setBounds(890, 460, 73, 23);

        jButton3.setBorderPainted(false);
        jButton3.setContentAreaFilled(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        Lab.add(jButton3);
        jButton3.setBounds(880, 0, 110, 30);

        ldeptbt.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        ldeptbt.setForeground(new java.awt.Color(0, 0, 51));
        ldeptbt.setText("By Department");
        ldeptbt.setContentAreaFilled(false);
        ldeptbt.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ldeptbtItemStateChanged(evt);
            }
        });
        ldeptbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ldeptbtActionPerformed(evt);
            }
        });
        Lab.add(ldeptbt);
        ldeptbt.setBounds(890, 140, 170, 25);
        Lab.add(jSeparator12);
        jSeparator12.setBounds(460, 220, 160, 10);

        jLabel24.setBackground(new java.awt.Color(255, 255, 255));
        jLabel24.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(0, 0, 51));
        jLabel24.setText("Lab Code:");
        Lab.add(jLabel24);
        jLabel24.setBounds(460, 200, 120, 20);

        ldeptip.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "CS", "EC", "EE", "Mech", "CV" }));
        ldeptip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ldeptipActionPerformed(evt);
            }
        });
        Lab.add(ldeptip);
        ldeptip.setBounds(900, 230, 90, 20);

        lsembt.setBackground(new java.awt.Color(0, 0, 51));
        lsembt.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        lsembt.setForeground(new java.awt.Color(0, 0, 51));
        lsembt.setText("Sem:");
        lsembt.setContentAreaFilled(false);
        lsembt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lsembtActionPerformed(evt);
            }
        });
        Lab.add(lsembt);
        lsembt.setBounds(900, 270, 90, 20);
        Lab.add(jSeparator13);
        jSeparator13.setBounds(900, 290, 130, 10);

        lsemip.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "1", "2", "3", "4", "5", "6", "7", "8" }));
        lsemip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lsemipActionPerformed(evt);
            }
        });
        Lab.add(lsemip);
        lsemip.setBounds(900, 300, 90, 20);

        jLabel25.setBackground(new java.awt.Color(255, 255, 255));
        jLabel25.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(0, 0, 51));
        jLabel25.setText("Select lab:");
        Lab.add(jLabel25);
        jLabel25.setBounds(900, 340, 110, 17);
        Lab.add(jSeparator14);
        jSeparator14.setBounds(900, 360, 160, 10);

        lsubip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lsubipActionPerformed(evt);
            }
        });
        Lab.add(lsubip);
        lsubip.setBounds(900, 370, 160, 30);

        jLabel2.setForeground(new java.awt.Color(0, 0, 51));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search 2.jpg"))); // NOI18N
        Lab.add(jLabel2);
        jLabel2.setBounds(0, 0, 1230, 680);

        Pack.add(Lab, "card3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Pack, javax.swing.GroupLayout.DEFAULT_SIZE, 1208, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Pack, javax.swing.GroupLayout.DEFAULT_SIZE, 677, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void scodebtItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_scodebtItemStateChanged
        scodeip.setEnabled(false);    // TODO add your handling code here:
    }//GEN-LAST:event_scodebtItemStateChanged

    private void scodebtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scodebtActionPerformed

        // TODO add your handling code here:
        if(scodebt.isSelected())
        {
            scodeip.setEnabled(true);
            deptbt.setSelected(false);
            coursebt.setSelected(false);
            schemebt.setSelected(false);
        }
        else
        scodeip.setEnabled(false);
    }//GEN-LAST:event_scodebtActionPerformed

    private void sembtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sembtActionPerformed

        // TODO add your handling code here:
        if(sembt.isSelected())
        {
            semip.setEnabled(true);
        }
        else
        {
            callsdeptsyl();
            semip.setEnabled(false);
        }
    }//GEN-LAST:event_sembtActionPerformed

    private void coursebtItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_coursebtItemStateChanged
        courseip.setEnabled(false);
        subip2.setEnabled(false);  // TODO add your handling code here:
    }//GEN-LAST:event_coursebtItemStateChanged

    private void coursebtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coursebtActionPerformed

        // TODO add your handling code here:
        if(coursebt.isSelected()){

            courseip.setEnabled(true);
            subip2.setEnabled(true);
            scodebt.setSelected(false);
            deptbt.setSelected(false);
            schemebt.setSelected(false);
        }
        else{
            courseip.setEnabled(false);
            subip2.setEnabled(false);

        }
    }//GEN-LAST:event_coursebtActionPerformed

    private void schemebtItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_schemebtItemStateChanged
        schemeip.setEnabled(false);
        subip3.setEnabled(false);    // TODO add your handling code here:
    }//GEN-LAST:event_schemebtItemStateChanged

    private void schemebtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_schemebtActionPerformed

        // TODO add your handling code here:
        if(schemebt.isSelected())
        {
            schemeip.setEnabled(true);
            subip3.setEnabled(true);
            scodebt.setSelected(false);
            deptbt.setSelected(false);
            coursebt.setSelected(false);

        }
        else{
            schemeip.setEnabled(false);
            subip3.setEnabled(false);

        }

    }//GEN-LAST:event_schemebtActionPerformed

    private void LogoutbuttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutbuttonMouseEntered
        lol.show(true);        // TODO add your handling code here:
    }//GEN-LAST:event_LogoutbuttonMouseEntered

    private void LogoutbuttonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutbuttonMouseExited
        lol.show(false);        // TODO add your handling code here:
    }//GEN-LAST:event_LogoutbuttonMouseExited

    private void LogoutbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutbuttonActionPerformed
        new Start(true).setVisible(true);
        this.dispose();  // TODO add your handling code here:
    }//GEN-LAST:event_LogoutbuttonActionPerformed

    private void AddbuttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddbuttonMouseEntered
        adl.show(true);        // TODO add your handling code here:
    }//GEN-LAST:event_AddbuttonMouseEntered

    private void AddbuttonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddbuttonMouseExited
        adl.show(false);        // TODO add your handling code here:
    }//GEN-LAST:event_AddbuttonMouseExited

    private void AddbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddbuttonActionPerformed
        new ADDMenu().setVisible(true);
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_AddbuttonActionPerformed

    private void UpdatebuttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UpdatebuttonMouseEntered
        upl.show(true);        // TODO add your handling code here:
    }//GEN-LAST:event_UpdatebuttonMouseEntered

    private void UpdatebuttonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UpdatebuttonMouseExited
        upl.show(false);        // TODO add your handling code here:
    }//GEN-LAST:event_UpdatebuttonMouseExited

    private void UpdatebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdatebuttonActionPerformed
        UpdateMenu up=new UpdateMenu();
        up.setVisible(true);
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_UpdatebuttonActionPerformed

    private void SearchbuttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SearchbuttonMouseEntered
        sel.show(true);        // TODO add your handling code here:
    }//GEN-LAST:event_SearchbuttonMouseEntered

    private void SearchbuttonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SearchbuttonMouseExited
        sel.show(false);        // TODO add your handling code here:
    }//GEN-LAST:event_SearchbuttonMouseExited

    private void DeletebuttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DeletebuttonMouseEntered
        del.show(true);        // TODO add your handling code here:
    }//GEN-LAST:event_DeletebuttonMouseEntered

    private void DeletebuttonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DeletebuttonMouseExited
        del.show(false);        // TODO add your handling code here:
    }//GEN-LAST:event_DeletebuttonMouseExited

    private void deptbtItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_deptbtItemStateChanged
        deptip.setEnabled(false);
        sembt.setSelected(false);
        sembt.setEnabled(false);
        subip1.setEnabled(false);
        semip.setEnabled(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_deptbtItemStateChanged

    private void deptbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deptbtActionPerformed
        if(deptbt.isSelected())
        {
            deptip.setEnabled(true);
            sembt.setEnabled(true);
            scodebt.setSelected(false);
            coursebt.setSelected(false);
            schemebt.setSelected(false);
            subip1.setEnabled(true);
        }
        else
        {
            deptip.setEnabled(false);
            sembt.setSelected(false);
            sembt.setEnabled(false);
            subip1.setEnabled(false);
            semip.setEnabled(false);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_deptbtActionPerformed

    private void subip2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subip2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_subip2ActionPerformed

    private void subip3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subip3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_subip3ActionPerformed

    private void subip1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subip1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_subip1ActionPerformed

    private void scodeipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scodeipActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_scodeipActionPerformed

    private void deptipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deptipActionPerformed

        callsdeptsyl();

        // TODO add your handling code here:
    }//GEN-LAST:event_deptipActionPerformed

    private void semipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_semipActionPerformed
        try{
            if(sembt.isSelected())
            {
                subip1.removeAllItems();
                String semester =semip.getSelectedItem().toString();

                String sql="select s.scode,s.sname "+
                "from subject s,department d "+
                "where d.branch='"+branch+"' and s.scode=d.scode and d.sem='"+semester+"'";
                rs=stmt.executeQuery(sql);
                if(rs.next())
                {
                    do{
                        String selement=rs.getString(1)+" "+rs.getString(2);
                        subip1.addItem(selement);
                    }while(rs.next());
                    rs.close();
                }
                else
                {
                    JOptionPane.showMessageDialog(rootPane,"no subject found for this department","Error",JOptionPane.ERROR_MESSAGE);
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(Search.class.getName()).log(Level.SEVERE, null, ex);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_semipActionPerformed

    private void courseipItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_courseipItemStateChanged

        // TODO add your handling code here:
    }//GEN-LAST:event_courseipItemStateChanged

    private void courseipMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_courseipMouseClicked

        // TODO add your handling code here:
    }//GEN-LAST:event_courseipMouseClicked

    private void courseipInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_courseipInputMethodTextChanged

        // TODO add your handling code here:
    }//GEN-LAST:event_courseipInputMethodTextChanged

    private void courseipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_courseipActionPerformed

        CourseInputFunction();
        // TODO add your handling code here:
    }//GEN-LAST:event_courseipActionPerformed

    private void schemeipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_schemeipActionPerformed

        String scheme=schemeip.getSelectedItem().toString();
        if(!scheme.equals("Select")){
            String sql="select scode,sname from subject where scheme='"+scheme+"'";

            try{

                rs=stmt.executeQuery(sql);
                subip3.removeAllItems();
                //subip3.addItem("select");
                if(rs.next())
                {

                    do{
                        subip3.addItem(rs.getString(1)+" "+rs.getString(2));
                    }while(rs.next());
                    rs.close();

                }
                else
                                           JOptionPane.showMessageDialog(null,"here no records found","error",JOptionPane.ERROR_MESSAGE);

            } catch (SQLException ex) {
                        JOptionPane.showMessageDialog(null,ex,"error",JOptionPane.ERROR_MESSAGE);
                
//Logger.getLogger(Search.class.getName()).log(Level.SEVERE, null, ex);
            }

        }

        // TODO add your handling code here:
    }//GEN-LAST:event_schemeipActionPerformed

    
    boolean callbycode(String code)
    {
        
        
       
        boolean res=false;
       
        try{
          
            int b=stmt.executeUpdate("delete from subject where scode='"+code+"'");
           
            if(b>0)
                res=true;
                        else return false;
            
        }    catch (SQLException ex) {
                 //Logger.getLogger(Search.class.getName()).log(Level.SEVERE, null, ex);
                 JOptionPane.showMessageDialog(rootPane,ex,"Error",JOptionPane.ERROR_MESSAGE);
             }
        return res;
        
    }
    
     public boolean callfordelete(Container ip)
    {
        JComboBox jbox=(JComboBox) ip;
        boolean res2=false;
        String temp=jbox.getSelectedItem().toString();
//        if(!temp.equals("select")){
        String code1="";
        int i=0;
        while(temp.charAt(i)!=' ')
        {
            code1=code1+temp.charAt(i);
            i++;
        }
        
        res2=callbycode(code1);
        if(res2)
            return true;
        else
            return false;
  /*      }
        else
        {
            JOptionPane.showMessageDialog(null,"Please select a subject frist");
            return false;
           
        }*/
    }
    
    
    
    
    
    
    
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        boolean r1=false;int chk=-1;
        if(scodebt.isSelected())
        {
            r1=callbycode(scodeip.getText().toString());

        }
        else if(deptbt.isSelected())
        {
            r1=callfordelete(subip1);
        }
        else if(coursebt.isSelected())
        {
            r1=callfordelete(subip2);
        }
        else if(schemebt.isSelected())
        {
            r1=callfordelete(subip3);
        }
        else
        {   chk+=1;
            JOptionPane.showMessageDialog(null,"no options selected","error",JOptionPane.ERROR_MESSAGE);
        }

        if(r1)
        {
                        JOptionPane.showMessageDialog(null," Subject successfully deleted","success",JOptionPane.INFORMATION_MESSAGE);

        }
        else if(!r1 && chk==-1)
        {
            JOptionPane.showMessageDialog(null,"Error","error",JOptionPane.ERROR_MESSAGE);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void gotolabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gotolabActionPerformed
        Pack.removeAll();
        Pack.add(Lab);
        Pack.repaint();
        Pack.revalidate();// TODO add your handling code here:
    }//GEN-LAST:event_gotolabActionPerformed

    private void majoripItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_majoripItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_majoripItemStateChanged

    private void majoripMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_majoripMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_majoripMouseClicked

    private void majoripInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_majoripInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_majoripInputMethodTextChanged

    private void majoripActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_majoripActionPerformed

        if(majorip.isEnabled()){
            String major=majorip.getSelectedItem().toString();
            subip2.removeAllItems();
            subip2.addItem("select");

            String sql="select c.scode,s.sname "+
            "from course c,subject s "+
            "where c.ctype='P.G' and c.major='"+major+"' and s.scode=c.scode";
            try{
                rs=stmt.executeQuery(sql);

                if(rs.next())
                {
                    subip2.addItem(rs.getString(1)+" "+rs.getString(2));
                }
                else
                {

                    JOptionPane.showMessageDialog(null,"here no records found","error",JOptionPane.ERROR_MESSAGE);

                }

            } catch (SQLException ex) {

                JOptionPane.showMessageDialog(null,ex,"error",JOptionPane.ERROR_MESSAGE);

                //Logger.getLogger(Search.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_majoripActionPerformed

    private void majorbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_majorbtActionPerformed

        try{
            if(majorbt.isSelected())
            {

                majorip.removeAllItems();
                String sql="select distinct c.major "+
                "from course c ";
                rs=stmt.executeQuery(sql);
                if(rs.next())
                {
                    do{
                        majorip.addItem(rs.getString(1));
                    }while(rs.next());
                    rs.close();

                    majorip.setEnabled(true);

                }
                else
                {
                    JOptionPane.showMessageDialog(null,"no records found","error",JOptionPane.ERROR_MESSAGE);
                }

            }
            else{
                majorip.setEnabled(false);
                CourseInputFunction();
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null,ex,"error",JOptionPane.ERROR_MESSAGE);
            //Logger.getLogger(Search.class.getName()).log(Level.SEVERE, null, ex);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_majorbtActionPerformed

    private void lscodebtItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_lscodebtItemStateChanged
        lscodeip.setEnabled(false);        // TODO add your handling code here:
    }//GEN-LAST:event_lscodebtItemStateChanged

    private void lscodebtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lscodebtActionPerformed
        if(lscodebt.isSelected())
        {
            lscodeip.setEnabled(true);
            labcodebt.setSelected(false);
            ldeptbt.setSelected(false);
        }
        else
        {
            lscodeip.setEnabled(false);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_lscodebtActionPerformed

    private void lscodeipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lscodeipActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lscodeipActionPerformed

    private void labcodebtItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_labcodebtItemStateChanged
        labcodeip.setEnabled(false);        // TODO add your handling code here:
    }//GEN-LAST:event_labcodebtItemStateChanged

    private void labcodebtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_labcodebtActionPerformed
        if(labcodebt.isSelected())
        {
            labcodeip.setEnabled(true);
            lscodebt.setSelected(false);
            ldeptbt.setSelected(false);
        }
        else
        {
            labcodeip.setEnabled(false);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_labcodebtActionPerformed

    private void labcodeipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_labcodeipActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_labcodeipActionPerformed

    private void Logoutbutton2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Logoutbutton2MouseEntered
        lol2.show(true);   // TODO add your handling code here:
    }//GEN-LAST:event_Logoutbutton2MouseEntered

    private void Logoutbutton2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Logoutbutton2MouseExited
        lol2.show(false);    // TODO add your handling code here:
    }//GEN-LAST:event_Logoutbutton2MouseExited

    private void Logoutbutton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Logoutbutton2ActionPerformed
        new Start(true).setVisible(true);
        this.dispose();   // TODO add your handling code here:
    }//GEN-LAST:event_Logoutbutton2ActionPerformed

    private void Addbutton2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Addbutton2MouseEntered
        adl2.show(true);        // TODO add your handling code here:
    }//GEN-LAST:event_Addbutton2MouseEntered

    private void Addbutton2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Addbutton2MouseExited
        adl2.show(false);     // TODO add your handling code here:
    }//GEN-LAST:event_Addbutton2MouseExited

    private void Addbutton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Addbutton2ActionPerformed
        new ADDMenu().setVisible(true);
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_Addbutton2ActionPerformed

    private void Updatebutton2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Updatebutton2MouseEntered
        upl2.show(true);   // TODO add your handling code here:
    }//GEN-LAST:event_Updatebutton2MouseEntered

    private void Updatebutton2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Updatebutton2MouseExited
        upl2.show(false); // TODO add your handling code here:
    }//GEN-LAST:event_Updatebutton2MouseExited

    private void Updatebutton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Updatebutton2ActionPerformed
        new UpdateMenu().setVisible(true);
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_Updatebutton2ActionPerformed

    private void Searchbutton2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Searchbutton2MouseEntered
        sel2.show(true);  // TODO add your handling code here:
    }//GEN-LAST:event_Searchbutton2MouseEntered

    private void Searchbutton2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Searchbutton2MouseExited
        sel2.show(false);// TODO add your handling code here:
    }//GEN-LAST:event_Searchbutton2MouseExited

    private void Deletebutton2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Deletebutton2MouseEntered
        del2.show(true);// TODO add your handling code here:
    }//GEN-LAST:event_Deletebutton2MouseEntered

    private void Deletebutton2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Deletebutton2MouseExited
        del2.show(false);// TODO add your handling code here:
    }//GEN-LAST:event_Deletebutton2MouseExited

    private void Deletebutton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Deletebutton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Deletebutton2ActionPerformed

    
    
     public boolean calllscode()
    {
        boolean r=false;
        try{
            
            
                    int re=stmt.executeUpdate("delete from labs where scode='"+lscodeip.getText()+"'");
                    if(re>0)
                    {
                        r=true;
                    }
                    else{
                        return false;
                    }

            
        } catch (SQLException ex) {
                      JOptionPane.showMessageDialog(null,ex,"error",JOptionPane.ERROR_MESSAGE);

//            Logger.getLogger(Search.class.getName()).log(Level.SEVERE, null, ex);
        }
        return r;
    }
     
     public boolean calllabcode(String llcode)
    {
        
         
        boolean r=false;
        try{
            
            
                    int re=stmt.executeUpdate("delete from labs where lcode='"+llcode+"'");
                    if(re>0)
                    {
                        r=true;
                    }
                    else
                    {
                            return false;
                    }
            
        } catch (SQLException ex) {
                      JOptionPane.showMessageDialog(null,ex,"error",JOptionPane.ERROR_MESSAGE);

//            Logger.getLogger(Search.class.getName()).log(Level.SEVERE, null, ex);
        }
        return r;
        
        
        
        
        
        
        
        
        
        
        
        
    }
     
     
     
     
     
     public boolean calbylabdept()
{
    boolean res2=false;
        String temp=lsubip.getSelectedItem().toString();
        
        String code1="";
        int i=0;
        while(temp.charAt(i)!=' ')
        {
            code1=code1+temp.charAt(i);
            i++;
        }
        
        res2=calllabcode(code1);
        if(res2)
            return true;
        else
            return false;
        
       
}
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        boolean r=false;int chk=-1;
        if(lscodebt.isSelected())
        {
            r=calllscode();
        }
        else if(labcodebt.isSelected())
        {
            r=calllabcode(labcodeip.getText().toString());
        }
        else if(ldeptbt.isSelected())
        {
            r=calbylabdept();
        }
        else
        {
            chk+=1;
            JOptionPane.showMessageDialog(null,"no option selected");
        }

        if(chk==-1 && r)
        {
                              JOptionPane.showMessageDialog(null,"lab successfully deleted");

        }
        else
                                  JOptionPane.showMessageDialog(null,"failed","error",JOptionPane.ERROR_MESSAGE);


        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        Pack.removeAll();
        Pack.add(Theory);
        Pack.repaint();
        Pack.revalidate();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void ldeptbtItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ldeptbtItemStateChanged

        ldeptip.setEnabled(false);
        lsembt.setEnabled(false);
        lsemip.setEnabled(false);
        lsubip.setEnabled(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_ldeptbtItemStateChanged

    private void ldeptbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ldeptbtActionPerformed

        if(ldeptbt.isSelected())
        {
            labcodebt.setSelected(false);
            lscodebt.setSelected(false);
            ldeptip.setEnabled(true);
            lsembt.setEnabled(true);

            lsubip.setEnabled(true);
        }
        else
        {
            ldeptip.setEnabled(false);
            lsembt.setEnabled(false);

            lsubip.setEnabled(false);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_ldeptbtActionPerformed
 public void callldeptsyl()
    {
        
 branch=ldeptip.getSelectedItem().toString();
            lsubip.removeAllItems();
           // lsubip.addItem("select");
            try{
                String sql="select distinct l.lcode,l.lname "+
                            "from department d,labs l "+
                            "where d.branch='"+branch+"' and l.scode=d.scode";
                rs=stmt.executeQuery(sql);
                if(rs.next())
                {
                    do{
                    String selement=rs.getString(1)+" "+rs.getString(2);
                    lsubip.addItem(selement);
                    }while(rs.next());
                    rs.close();
                }
                else
                {
                    JOptionPane.showMessageDialog(rootPane,"no subject found for this department","Error",JOptionPane.ERROR_MESSAGE);
                }
                 
                
            } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane,ex,"Error",JOptionPane.ERROR_MESSAGE);
                    //Logger.getLogger(Search.class.getName()).log(Level.SEVERE, null, ex);
        }
            
    }

    private void ldeptipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ldeptipActionPerformed

        callldeptsyl();

        // TODO add your handling code here:
    }//GEN-LAST:event_ldeptipActionPerformed

    private void lsembtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lsembtActionPerformed
        if(lsembt.isSelected())
        {
            lsemip.setEnabled(true);
        }
        else
        {
            callldeptsyl();
            lsemip.setEnabled(false);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_lsembtActionPerformed

    private void lsemipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lsemipActionPerformed

        try{
            if(lsembt.isSelected())
            {
                lsubip.removeAllItems();
                String semester =lsemip.getSelectedItem().toString();

                String sql="select distinct l.lcode,l.lname "+
                "from labs l,department d "+
                "where d.branch='"+ldeptip.getSelectedItem().toString()+"' and l.scode=d.scode and d.sem='"+semester+"'";
                rs=stmt.executeQuery(sql);
                if(rs.next())
                {
                    do{
                        String selement=rs.getString(1)+" "+rs.getString(2);
                        lsubip.addItem(selement);
                    }while(rs.next());
                    rs.close();
                }
                else
                {
                    JOptionPane.showMessageDialog(rootPane,"no subject found for this department","Error",JOptionPane.ERROR_MESSAGE);
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(Search.class.getName()).log(Level.SEVERE, null, ex);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_lsemipActionPerformed

    private void lsubipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lsubipActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lsubipActionPerformed

    private void SearchbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchbuttonActionPerformed
new Search(false).setVisible(true);
this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_SearchbuttonActionPerformed

    private void DeletebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeletebuttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DeletebuttonActionPerformed
public void callsdeptsyl()
{
    branch=deptip.getSelectedItem().toString();
            subip1.removeAllItems();
//            subip1.addItem("select");
            try{
                String sql="select s.scode,s.sname "+
                            "from subject s,department d "+
                            "where d.branch='"+branch+"' and s.scode=d.scode";
                rs=stmt.executeQuery(sql);
                if(rs.next())
                {
                    do{
                    String selement=rs.getString(1)+" "+rs.getString(2);
                    subip1.addItem(selement);
                    }while(rs.next());
                    rs.close();
                }
                else
                {
                    JOptionPane.showMessageDialog(rootPane,"no subject found for this department","Error",JOptionPane.ERROR_MESSAGE);
                }
                 
                
            } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane,ex,"Error",JOptionPane.ERROR_MESSAGE);
                    //Logger.getLogger(Search.class.getName()).log(Level.SEVERE, null, ex);
        }
            

}  public void CourseInputFunction()
    {
           try{
            if(coursebt.isSelected())
            {
                subip2.removeAllItems();
                subip2.addItem("select");
                String course=courseip.getSelectedItem().toString();
                 if(course=="P.G")
                     majorbt.setEnabled(true);
                 else
                     majorbt.setEnabled(false);
                 
                              
                 String sql="select s.scode,s.sname "+
                            "from subject s "+
                            "where s.ctype='"+course+"' ";
                rs=stmt.executeQuery(sql);
                if(rs.next())
                {
                    do{
                    subip2.addItem(rs.getString(1)+" "+rs.getString(2));
                    }while(rs.next());
                    rs.close();
                }
                else
                {
                    JOptionPane.showMessageDialog(null,"no records found","error",JOptionPane.ERROR_MESSAGE);
                }
                
                
            }
        } catch (SQLException ex) {
JOptionPane.showMessageDialog(null,ex,"error",JOptionPane.ERROR_MESSAGE);            
//Logger.getLogger(Search.class.getName()).log(Level.SEVERE, null, ex);
        }

    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Delete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Delete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Delete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Delete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Delete().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Addbutton;
    private javax.swing.JButton Addbutton2;
    private javax.swing.JButton Deletebutton;
    private javax.swing.JButton Deletebutton2;
    private javax.swing.JPanel Lab;
    private javax.swing.JButton Logoutbutton;
    private javax.swing.JButton Logoutbutton2;
    private javax.swing.JPanel Pack;
    private javax.swing.JButton Searchbutton;
    private javax.swing.JButton Searchbutton2;
    private javax.swing.JPanel Theory;
    private javax.swing.JButton Updatebutton;
    private javax.swing.JButton Updatebutton2;
    private javax.swing.JLabel adl;
    private javax.swing.JLabel adl2;
    private javax.swing.JRadioButton coursebt;
    private javax.swing.JComboBox<String> courseip;
    private javax.swing.JLabel del;
    private javax.swing.JLabel del2;
    private javax.swing.JRadioButton deptbt;
    private javax.swing.JComboBox<String> deptip;
    private javax.swing.JButton gotolab;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JRadioButton labcodebt;
    private javax.swing.JTextField labcodeip;
    private javax.swing.JRadioButton ldeptbt;
    private javax.swing.JComboBox<String> ldeptip;
    private javax.swing.JLabel lol;
    private javax.swing.JLabel lol2;
    private javax.swing.JRadioButton lscodebt;
    private javax.swing.JTextField lscodeip;
    private javax.swing.JRadioButton lsembt;
    private javax.swing.JComboBox<String> lsemip;
    private javax.swing.JComboBox<String> lsubip;
    private javax.swing.JRadioButton majorbt;
    private javax.swing.JComboBox<String> majorip;
    private javax.swing.JRadioButton schemebt;
    private javax.swing.JComboBox<String> schemeip;
    private javax.swing.JRadioButton scodebt;
    private javax.swing.JTextField scodeip;
    private javax.swing.JLabel sel;
    private javax.swing.JLabel sel2;
    private javax.swing.JRadioButton sembt;
    private javax.swing.JComboBox<String> semip;
    private javax.swing.JComboBox<String> subip1;
    private javax.swing.JComboBox<String> subip2;
    private javax.swing.JComboBox<String> subip3;
    private javax.swing.JLabel upl;
    private javax.swing.JLabel upl2;
    // End of variables declaration//GEN-END:variables
}
