
import java.awt.Container;
import java.awt.Dimension;
import java.awt.Image;
import java.io.FileReader;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Aayush
 */
public class Start extends javax.swing.JFrame {

    /**
     * Creates new form Start
     */
    
    boolean op;
    public Start() {
        
        
        
      
        initComponents();
        desc.show(false);
        op=false;
        jLabel6.show(false);        // TODO add your handling code here:
        jLabel7.show(false);        // TODO add your handling code here:

         adl.show(false);
         upl.show(false);
         del.show(false);
         sel.show(false);
         lol.show(false);
       
          
    }

    public Start(boolean o)
    {
        initComponents();
        
     op=o;
        
        
         
        jLabel6.show(false);        // TODO add your handling code here:
        jLabel7.show(false);        // TODO add your handling code here:

         adl.show(false);
         upl.show(false);
         del.show(false);
         sel.show(false);
         lol.show(false);
        Addbutton.setToolTipText("ADD SYLLABUS");
         Updatebutton.setToolTipText("UPDATE SYLLABUS");
         Searchbutton.setToolTipText("SEARCH SYLLABUS");
          Deletebutton.setToolTipText("REMOVE/DELETE SYLLABUS");
          Logoutbutton.setToolTipText("LOGOUT");
        
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Pack = new javax.swing.JPanel();
        login = new javax.swing.JPanel();
        loading = new javax.swing.JLabel();
        test = new javax.swing.JLabel();
        loginip = new javax.swing.JTextField();
        passip = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        loginbt = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        MainMenu = new javax.swing.JPanel();
        Updatebutton = new javax.swing.JButton();
        Searchbutton = new javax.swing.JButton();
        Deletebutton = new javax.swing.JButton();
        Logoutbutton = new javax.swing.JButton();
        Addbutton = new javax.swing.JButton();
        adl = new javax.swing.JLabel();
        upl = new javax.swing.JLabel();
        sel = new javax.swing.JLabel();
        del = new javax.swing.JLabel();
        lol = new javax.swing.JLabel();
        desc = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        Pack.setLayout(new java.awt.CardLayout());

        login.setOpaque(false);
        login.setLayout(null);

        loading.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        loading.setForeground(new java.awt.Color(255, 255, 255));
        login.add(loading);
        loading.setBounds(480, 10, 400, 20);

        test.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bookswal3.jpg"))); // NOI18N
        test.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                testMouseClicked(evt);
            }
        });
        login.add(test);
        test.setBounds(0, 0, 900, 500);

        loginip.setBackground(new java.awt.Color(0, 0, 0));
        loginip.setForeground(new java.awt.Color(255, 255, 255));
        loginip.setBorder(null);
        login.add(loginip);
        loginip.setBounds(400, 210, 170, 30);

        passip.setBackground(new java.awt.Color(0, 0, 0));
        passip.setForeground(new java.awt.Color(255, 255, 255));
        passip.setBorder(null);
        passip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passipActionPerformed(evt);
            }
        });
        login.add(passip);
        passip.setBounds(400, 320, 170, 30);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/businessman.png"))); // NOI18N
        login.add(jLabel3);
        jLabel3.setBounds(330, 180, 80, 70);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/padlock.png"))); // NOI18N
        login.add(jLabel4);
        jLabel4.setBounds(330, 290, 70, 70);
        login.add(jSeparator1);
        jSeparator1.setBounds(400, 350, 170, 30);
        login.add(jSeparator2);
        jSeparator2.setBounds(400, 240, 170, 30);

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Login");
        login.add(jLabel5);
        jLabel5.setBounds(430, 100, 80, 30);

        loginbt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/login.png"))); // NOI18N
        loginbt.setContentAreaFilled(false);
        loginbt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                loginbtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                loginbtMouseExited(evt);
            }
        });
        loginbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginbtActionPerformed(evt);
            }
        });
        login.add(loginbt);
        loginbt.setBounds(410, 370, 90, 60);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/meeting.png"))); // NOI18N
        jButton1.setContentAreaFilled(false);
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton1MouseExited(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        login.add(jButton1);
        jButton1.setBounds(770, 370, 90, 70);

        jLabel6.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Login");
        login.add(jLabel6);
        jLabel6.setBounds(440, 430, 80, 20);

        jLabel7.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Login as guest");
        login.add(jLabel7);
        jLabel7.setBounds(770, 450, 120, 15);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/start2.jpg"))); // NOI18N
        login.add(jLabel1);
        jLabel1.setBounds(-10, -10, 930, 530);

        Pack.add(login, "card3");

        MainMenu.setLayout(null);

        Updatebutton.setBackground(new java.awt.Color(255, 255, 255));
        Updatebutton.setForeground(new java.awt.Color(255, 255, 255));
        Updatebutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/rotate.png"))); // NOI18N
        Updatebutton.setBorderPainted(false);
        Updatebutton.setContentAreaFilled(false);
        Updatebutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                UpdatebuttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                UpdatebuttonMouseExited(evt);
            }
        });
        Updatebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdatebuttonActionPerformed(evt);
            }
        });
        MainMenu.add(Updatebutton);
        Updatebutton.setBounds(350, 150, 90, 120);

        Searchbutton.setBackground(new java.awt.Color(255, 255, 255));
        Searchbutton.setForeground(new java.awt.Color(255, 255, 255));
        Searchbutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search (1).png"))); // NOI18N
        Searchbutton.setBorderPainted(false);
        Searchbutton.setContentAreaFilled(false);
        Searchbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SearchbuttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SearchbuttonMouseExited(evt);
            }
        });
        Searchbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchbuttonActionPerformed(evt);
            }
        });
        MainMenu.add(Searchbutton);
        Searchbutton.setBounds(490, 170, 80, 90);

        Deletebutton.setBackground(new java.awt.Color(255, 255, 255));
        Deletebutton.setForeground(new java.awt.Color(255, 255, 255));
        Deletebutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/shopping-basket.png"))); // NOI18N
        Deletebutton.setBorderPainted(false);
        Deletebutton.setContentAreaFilled(false);
        Deletebutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                DeletebuttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                DeletebuttonMouseExited(evt);
            }
        });
        Deletebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeletebuttonActionPerformed(evt);
            }
        });
        MainMenu.add(Deletebutton);
        Deletebutton.setBounds(610, 170, 90, 90);

        Logoutbutton.setFont(new java.awt.Font("Tahoma", 0, 3)); // NOI18N
        Logoutbutton.setForeground(new java.awt.Color(255, 255, 255));
        Logoutbutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/door.png"))); // NOI18N
        Logoutbutton.setText("vv");
        Logoutbutton.setContentAreaFilled(false);
        Logoutbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LogoutbuttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LogoutbuttonMouseExited(evt);
            }
        });
        Logoutbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutbuttonActionPerformed(evt);
            }
        });
        MainMenu.add(Logoutbutton);
        Logoutbutton.setBounds(60, 360, 40, 60);

        Addbutton.setBackground(new java.awt.Color(255, 255, 255));
        Addbutton.setFont(new java.awt.Font("Tahoma", 0, 3)); // NOI18N
        Addbutton.setForeground(new java.awt.Color(51, 51, 51));
        Addbutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/file.png"))); // NOI18N
        Addbutton.setText("v");
        Addbutton.setBorderPainted(false);
        Addbutton.setContentAreaFilled(false);
        Addbutton.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                AddbuttonFocusGained(evt);
            }
        });
        Addbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                AddbuttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                AddbuttonMouseExited(evt);
            }
        });
        Addbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddbuttonActionPerformed(evt);
            }
        });
        MainMenu.add(Addbutton);
        Addbutton.setBounds(200, 160, 120, 100);

        adl.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        adl.setForeground(new java.awt.Color(255, 255, 255));
        adl.setText("ADD");
        MainMenu.add(adl);
        adl.setBounds(220, 130, 60, 17);

        upl.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        upl.setForeground(new java.awt.Color(255, 255, 255));
        upl.setText("Update");
        MainMenu.add(upl);
        upl.setBounds(360, 130, 100, 17);

        sel.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        sel.setForeground(new java.awt.Color(255, 255, 255));
        sel.setText("Search");
        MainMenu.add(sel);
        sel.setBounds(500, 130, 100, 17);

        del.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        del.setForeground(new java.awt.Color(255, 255, 255));
        del.setText("Delete");
        MainMenu.add(del);
        del.setBounds(630, 130, 90, 17);

        lol.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        lol.setForeground(new java.awt.Color(255, 255, 255));
        lol.setText("Logout");
        MainMenu.add(lol);
        lol.setBounds(50, 320, 120, 17);

        desc.setFont(new java.awt.Font("Perpetua", 3, 18)); // NOI18N
        desc.setForeground(new java.awt.Color(255, 255, 255));
        MainMenu.add(desc);
        desc.setBounds(140, 320, 700, 80);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Untitled.jpg"))); // NOI18N
        MainMenu.add(jLabel2);
        jLabel2.setBounds(-10, -13, 940, 530);

        Pack.add(MainMenu, "card2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Pack, javax.swing.GroupLayout.DEFAULT_SIZE, 900, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Pack, javax.swing.GroupLayout.DEFAULT_SIZE, 499, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

   
    
    
    private void AddbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddbuttonActionPerformed

                ADDMenu mm=new ADDMenu();
                mm.setVisible(true);
                this.dispose();
                

               


        // TODO add your handling code here:
    }//GEN-LAST:event_AddbuttonActionPerformed

    private void AddbuttonFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_AddbuttonFocusGained

            


        // TODO add your handling code here:
    }//GEN-LAST:event_AddbuttonFocusGained

    private void AddbuttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddbuttonMouseEntered

        
        adl.show(true); 
        String dis="You can add a subject/lab and its syllabus !";
                    
        desc.setText(dis);
        desc.show(true);// TODO add your handling code here:
    }//GEN-LAST:event_AddbuttonMouseEntered

    private void AddbuttonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddbuttonMouseExited

        adl.show(false);
        desc.show(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_AddbuttonMouseExited

    private void UpdatebuttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UpdatebuttonMouseEntered
upl.show(true);        
desc.setText("You can update details/syllabus of an existing subject/lab");
desc.show(true);// TODO add your handling code here:
    }//GEN-LAST:event_UpdatebuttonMouseEntered

    private void UpdatebuttonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UpdatebuttonMouseExited
upl.show(false);
desc.show(false);// TODO add your handling code here:
    }//GEN-LAST:event_UpdatebuttonMouseExited

    private void SearchbuttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SearchbuttonMouseEntered
sel.show(true);
desc.setText("You can search syllabus of an existing subject/lab");
desc.show(true);
// TODO add your handling code here:
    }//GEN-LAST:event_SearchbuttonMouseEntered

    private void SearchbuttonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SearchbuttonMouseExited
sel.show(false);
desc.show(false);// TODO add your handling code here:
    }//GEN-LAST:event_SearchbuttonMouseExited

    private void DeletebuttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DeletebuttonMouseEntered
del.show(true);  
desc.setText("You can remove a Subject/lab");
desc.show(true);
// TODO add your handling code here:
    }//GEN-LAST:event_DeletebuttonMouseEntered

    private void DeletebuttonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DeletebuttonMouseExited
del.show(false);
desc.show(false);// TODO add your handling code here:
    }//GEN-LAST:event_DeletebuttonMouseExited

    private void UpdatebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdatebuttonActionPerformed
UpdateMenu up=new UpdateMenu();
up.setVisible(true);
this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_UpdatebuttonActionPerformed

    private void SearchbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchbuttonActionPerformed
    new Search(false).setVisible(true);
    this.dispose();
    // TODO add your handling code here:
    }//GEN-LAST:event_SearchbuttonActionPerformed

    private void DeletebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeletebuttonActionPerformed
 Search sc=new Search(false);
sc.setButton();
sc.setVisible(true);
this.dispose();    // TODO add your handling code here:
    }//GEN-LAST:event_DeletebuttonActionPerformed

    private void passipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passipActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passipActionPerformed

    private void LogoutbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutbuttonActionPerformed
        Pack.removeAll();
Pack.add(login);
Pack.repaint();
Pack.revalidate();// TODO add your handling code here:
    }//GEN-LAST:event_LogoutbuttonActionPerformed

    private void LogoutbuttonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutbuttonMouseExited
        lol.show(false);        // TODO add your handling code here:
    }//GEN-LAST:event_LogoutbuttonMouseExited

    private void LogoutbuttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutbuttonMouseEntered
        lol.show(true);        // TODO add your handling code here:
    }//GEN-LAST:event_LogoutbuttonMouseEntered

    private void loginbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginbtActionPerformed

        
        String log=loginip.getText().toString();
        char pas[]=passip.getPassword();
        String passw=String.valueOf(pas);
            if(log.equals("root") && passw.equals("root123"))
            {
                
                //Image i=new ImageIO.read(getClass().getResource("/images/unlocked.png"));
                //loginbt.setIcon(i);
               // JOptionPane.showMessageDialog(null,"successful");
                Pack.removeAll();
                Pack.add(MainMenu);
                Pack.repaint();
                Pack.revalidate();
               loginip.setText("");
               passip.setText("");
            }
            else
                JOptionPane.showMessageDialog(null,"login failed,wrong username or password","eooro",JOptionPane.ERROR_MESSAGE);
            





        




        // TODO add your handling code here:
    }//GEN-LAST:event_loginbtActionPerformed

    private void jButton1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseEntered
jLabel7.show(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1MouseEntered

    private void jButton1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseExited
jLabel7.show(false);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1MouseExited

    private void loginbtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginbtMouseEntered
jLabel6.show(true);        // TODO add your handling code here:
    }//GEN-LAST:event_loginbtMouseEntered

    private void loginbtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginbtMouseExited
jLabel6.show(false);        // TODO add your handling code here:
    }//GEN-LAST:event_loginbtMouseExited

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      
        //JOptionPane.showMessageDialog(null,"Guest users are not allowed to make any changes in the syllabus","Note",JOptionPane.QUESTION_MESSAGE ); // TODO add your handling code here:
int reply=JOptionPane.showConfirmDialog(null,"guest users are not allowed to manupulate syllabus", "note",JOptionPane.OK_CANCEL_OPTION);

if(reply==JOptionPane.OK_OPTION)
{
    Search sobj=new Search(true);
    sobj.setVisible(true);
    this.dispose();
    
}
    }//GEN-LAST:event_jButton1ActionPerformed

    private void testMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_testMouseClicked
        if(op){     
        threadgenerate th=new threadgenerate(test);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_testMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        if(!op){
 loadingtest th=new loadingtest(loading,test);
        }
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Start.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Start.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Start.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Start.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Start().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Addbutton;
    private javax.swing.JButton Deletebutton;
    private javax.swing.JButton Logoutbutton;
    private javax.swing.JPanel MainMenu;
    private javax.swing.JPanel Pack;
    private javax.swing.JButton Searchbutton;
    private javax.swing.JButton Updatebutton;
    private javax.swing.JLabel adl;
    private javax.swing.JLabel del;
    private javax.swing.JLabel desc;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel loading;
    private javax.swing.JPanel login;
    private javax.swing.JButton loginbt;
    private javax.swing.JTextField loginip;
    private javax.swing.JLabel lol;
    private javax.swing.JPasswordField passip;
    private javax.swing.JLabel sel;
    private javax.swing.JLabel test;
    private javax.swing.JLabel upl;
    // End of variables declaration//GEN-END:variables
}

   class threadgenerate implements Runnable
{

    JLabel jb;
    Thread t1;
       Dimension dm=new Dimension();
    threadgenerate(Container jlb)
    {
        jb=(JLabel) jlb;
       t1=new Thread(this);
        t1.start();
      
    }
    
    
    @Override
    public void run() {
     
        do{
            try {
                dm=jb.getSize();
                int h=dm.height;
                int w=dm.width;
                h=h-10;
                jb.setSize(w, h);
                
                t1.sleep(5);
            } catch (InterruptedException ex) {
                Logger.getLogger(threadgenerate.class.getName()).log(Level.SEVERE, null, ex);
            }
        }while(dm.height!=0);
        
}
   }

class loadingtest implements Runnable
{
    Thread t;
    JLabel jl,j2;
    loadingtest(Container j,Container k)
    {
        t=new Thread(this);
        jl=(JLabel) j;
        j2=(JLabel) k;
        t.start();
    }
    
    public void run()
    {
        try {
          
            //FileReader fr=new FileReader(" C:\\Users\\Aayush\\Documents\\NetBeansProjects\\xmp");
           // Runtime run=Runtime.getRuntime();
            //Process pro=run.exec("C:\\Users\\Aayush\\Documents\\NetBeansProjects\\xmp.exe.ink");
            
            t.sleep(500);
            jl.setText("Loading database modules.");
            t.sleep(400);
            jl.setText("Loading database modules. .");
            t.sleep(400);
            jl.setText("Loading database modules. . .");
            t.sleep(400);
            jl.setText("Loading database modules. . . .");
            t.sleep(400);
             jl.setText("Loading database modules. . . . .");
            t.sleep(400);
             jl.setText("Loading database modules. . . . . .");
            t.sleep(400);
             jl.setText("Loading database modules. . . . . . .");
            t.sleep(400);
             jl.setText("Loading database modules. . . . . . . .");
            t.sleep(400);
             jl.setText("Loading database modules. . . . . . . . .");
           t.sleep(400);
             jl.setText("Loading database modules. . . . . . . . . .");
            /*t.sleep(600);
             jl.setText("Loading database modules. . . . . . . . . . .");
            t.sleep600);
             jl.setText("Loading database modules. . . . . . . . . . . .");*/
            t.sleep(600);
            jl.setText("Database ready !!");
            t.sleep(600);
           jl.setEnabled(false);
            jl.show(false);
             
           threadgenerate th=new threadgenerate(j2);
                    } catch (InterruptedException ex) {
            Logger.getLogger(loadingtest.class.getName()).log(Level.SEVERE, null, ex);
        } /*catch (IOException ex) {
            Logger.getLogger(loadingtest.class.getName()).log(Level.SEVERE, null, ex);
        } */
        
    }
            
}